### ISSUE TITLE
Falling block entity renderes lighter than real blocks (not ambient occlusion)

### ISSUE THREAD

**Issue by SolidBlock-cn** [grondag/canvas#103]
If you place together real blocks and falling blocks, then you will find the falling block entity is obviously lighter (whiter) than real blocks. This does not happen in vanilla rendering of some OptiFine shaders.
And, if you could make the falling blocks of waving blocks (grass, leaves, etc.) wave like real blocks, it would be better.

**Comment by eristhea** [comment]
Don't want to open a new issue as this one covers it but I can add some more info.

When gravity-affected blocks are falling, their light level is much higher than it should be. I tested on the internal server in vanilla/fabric with the latest release on Curseforge (1.0.933) and the latest Github release (1.0.974). Both have this issue.

**Comment by grondag** [comment]
Thank you for the reports.  

This is part of #53 but that wasn't clear.  I've updated the description there.  This is being actively worked as part of a major change to rendering that will handle entities, etc. with shaders.
