### ISSUE TITLE
Add zh-cn (simplified Chinese) or other languages translation

### ISSUE THREAD

**Issue by SolidBlock-cn** [grondag/canvas#104]
Adding translation will make non-English readers config the Canvas more easily.

**Comment by grondag** [comment]
I am happy to accept translation PRs.  I don't have any ability to do them myself.

**Comment by spiralhalo** [comment]
Someone did it https://github.com/vram-guild/canvas/pull/377

I'm gonna close this since there is also #77 asking other languages
