### ISSUE TITLE
Wrong lighting on certain model quads

### ISSUE THREAD

**Issue by paulevsGitch** [grondag/canvas#111]
Sometimes block quads renders as black or white, partially independent of options and AO/Diffuse lighting. This happens to random quads of complex models with size smaller than one block

![2020-10-08_20 30 26](https://user-images.githubusercontent.com/17707380/95494056-f800fc00-09a5-11eb-8af5-fe82979227fd.png)

**Comment by grondag** [comment]
What block is in the picture? Looks useful for testing.

**Comment by paulevsGitch** [comment]
This is bubble coral from my upcoming mod, its model is here
- [blockstate json](https://github.com/paulevsGitch/BetterEnd/blob/master/src/main/resources/assets/betterend/blockstates/bubble_coral.json)
- [block model](https://github.com/paulevsGitch/BetterEnd/blob/master/src/main/resources/assets/betterend/models/block/bubble_coral_1.json)
- [block code](https://github.com/paulevsGitch/BetterEnd/blob/master/src/main/java/ru/betterend/blocks/BlockBubbleCoral.java) (if necessary)

I tried to fix it with shader, disabling AO and Diffuse have small effect, but quads are still wrong shaded
- [material map](https://github.com/paulevsGitch/BetterEnd/blob/master/src/main/resources/assets/betterend/materialmaps/block/bubble_coral.json)
- [material](https://github.com/paulevsGitch/BetterEnd/blob/master/src/main/resources/assets/betterend/materials/noao.json)

I saw the same issue on wall mushrooms from [Better Nether](https://www.curseforge.com/minecraft/mc-mods/betternether) mod. Probably this is related to small vertex size or their random rotation

**Comment by grondag** [comment]
Thank you for the extra detail.  Does it look correct with Indigo when Canvas isn't running? (indigo is the default renderer that comes with Fabric.)

**Comment by paulevsGitch** [comment]
Yes, Indigo rendering is correct

Indigo:
![2020-10-10_00 26 24](https://user-images.githubusercontent.com/17707380/95632908-4e963500-0a8f-11eb-9ce2-a1f1dd190bcb.png)

Canvas:
![2020-10-10_00 23 10](https://user-images.githubusercontent.com/17707380/95632906-4d650800-0a8f-11eb-8d2e-a183d1e4a65f.png)

**Comment by grondag** [comment]
Should be fixed in the most recent GitHub build.  Curseforge release still a ways off.

Please advise if still occurring.
