### ISSUE TITLE
Connected Textures Mod (or compatibility)? 

### ISSUE THREAD

**Issue by ghost** [grondag/canvas#112]
I don't know what kind of a topic about connected textures mod is, but I know exactly what I would like CTM support in "canvas" mods. At least because the illusions with the increased size of the player by 2 times, and textures 8x8 (in our case it's some "F8thful") are very sensitive to pixel variations.

**Comment by ghost** [comment]
You can use "Connected Block Textures" to do this.
https://github.com/Nuclearfarts/connected-block-textures

**Comment by spiralhalo** [comment]
What is this issue about? Connected textures are available in several mods

CBT https://github.com/Nuclearfarts/connected-block-textures
CBT unofficial 1.17 port https://github.com/HyperCubeMC/connected-block-textures
CTMF https://www.curseforge.com/minecraft/mc-mods/ctm-fabric

They are known to be compatible with Canvas.
