### ISSUE TITLE
Crash: Void_air block 

### ISSUE THREAD

**Issue by Lordbaane** [grondag/canvas#114]
---- Minecraft Crash Report ----
// Don't do that.

Time: 15/10/20 8:45 PM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} as it does not exist in Block{minecraft:void_air}
	at net.minecraft.class_2688.method_11654(class_2688.java:95)
	at net.rotten.WoodReckRenderer.render(WoodReckRenderer.java:24)
	at net.rotten.WoodReckRenderer.method_3569(WoodReckRenderer.java:14)
	at net.minecraft.class_824.method_23079(class_824.java:107)
	at net.minecraft.class_824.method_23081(class_824.java:96)
	at net.minecraft.class_824.method_3554(class_824.java:128)
	at net.minecraft.class_824.method_3555(class_824.java:96)
	at grondag.canvas.render.CanvasWorldRenderer.renderWorld(CanvasWorldRenderer.java:604)
	at grondag.canvas.render.CanvasWorldRenderer.method_22710(CanvasWorldRenderer.java:1144)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.redirect$zla000$redirectRenderingWorld(class_757.java:2545)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1023)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2688.method_11654(class_2688.java:95)
	at net.rotten.WoodReckRenderer.render(WoodReckRenderer.java:24)
	at net.rotten.WoodReckRenderer.method_3569(WoodReckRenderer.java:14)
	at net.minecraft.class_824.method_23079(class_824.java:107)
	at net.minecraft.class_824.method_23081(class_824.java:96)

-- Block Entity Details --
Details:
	Name: rotten:woodreckentity // net.rotten.WoodReckEntity
	Block: Block{rotten:woodreck}[facing=west,waterlogged=false]
	Block location: World: (-159,69,-165), Chunk: (at 1,4,11 in -10,-11; contains blocks -160,0,-176 to -145,255,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Block: Block{minecraft:void_air}
	Block location: World: (-159,69,-165), Chunk: (at 1,4,11 in -10,-11; contains blocks -160,0,-176 to -145,255,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.minecraft.class_824.method_3554(class_824.java:128)
	at net.minecraft.class_824.method_3555(class_824.java:96)
	at grondag.canvas.render.CanvasWorldRenderer.renderWorld(CanvasWorldRenderer.java:604)
	at grondag.canvas.render.CanvasWorldRenderer.method_22710(CanvasWorldRenderer.java:1144)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.redirect$zla000$redirectRenderingWorld(class_757.java:2545)

-- Affected level --
Details:
	All players: 1 total; [class_746['LordBaane'/122, l='ClientLevel', x=-142.50, y=69.00, z=-160.50]]
	Chunk stats: Client Chunks (ImmPtl) 599
	Level dimension: minecraft:overworld
	Level spawn location: World: (-256,65,-256), Chunk: (at 0,4,0 in -16,-16; contains blocks -256,0,-256 to -241,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1527067 game time, 2031824 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at net.minecraft.class_310.method_1514(class_310.java:674)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2308812000 bytes (2201 MB) / 4715446272 bytes (4497 MB) up to 7529299968 bytes (7180 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx8077m
	Fabric Mods: 
		adabraniummod: Adabranium Mod 1.2.1
		adapaxels: AdaPaxels 1.0.3
		adorn: Adorn 1.11.1+1.16.3
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.6
		adventurez: AdventureZ 1.1.2
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		autoconfig1u: Auto Config v1 Updated 3.2.2
		backpackmod: Backpack Mod 1.16.3-1.2.2
		backslot: BackSlot 1.1.5
		bettercaves: YUNG's Better Caves 1.16.2-1.0.2
		betternether: Better Nether 4.1.4
		blue_endless_jankson: jankson 1.1.2
		bowinfinityfix: Bow Infinity Fix rv9
		byg: BYG 1.0.13
		canvas: Canvas Renderer 1.0.989
		cardinal-components-base: Cardinal Components API (base) 2.6.0
		cardinal-components-entity: Cardinal Components API (entities) 2.6.0
		cardinal-components-item: Cardinal Components API (items) 2.6.0
		carrier: Carrier 1.3.0
		carvepump: Carve My Pumpkin 1.0.2
		cavebiomes: Cave Biomes 0.4.0
		chainmail: Chainmail 0.5.0
		cleanview: CleanView 1.16.3-v1-fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.8.2
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.8
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		couplings: Couplings 1.3.1
		curios: Curios API 0.0.8-1.16.3
		dawn: Dawn API 1.2
		disablecustomworldsadvice: Disable Custom Worlds Advice 1.1
		durabilityviewer: Giselbaers Durability Viewer 1.16.2-fabric0.17.2-1.8.7
		earthtojavamobs: Earth2Java 1.2.1+1.16.3
		economical_villager_trading: Economical Villager Trading 1.0.1-1+1.16.1-1.16.3
		elytra-recipe: Elytra Recipe 1.0.1
		expandedstorage: ExpandedStorage 5.6.30
		fabric: Fabric API 0.24.0+build.411-1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
		fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.2+f8ac1db295
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963695
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-language-scala: Fabric Language Scala 0.3.2.12
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5fa7
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.0+c270b09895
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea18895
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.0+9f0fb4b895
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.1+f8ac1db295
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.1+f8ac1db295
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb895
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.3+f8ac1db295
		fabricloader: Fabric Loader 0.10.1+build.209
		falling_tree: FallingTree 2.4.0
		fermion: Fermion 2.6.206
		fermion-orientation: Fermion Orientation 1.1.205
		fermion-varia: Fermion Varia 2.4.206
		fiber: fiber 0.23.0-2
		flyring: Ring of Flight 0.1.0+1.16.3
		frex: FREX 3.4.140
		gbfabrictools: GBfabrictools 1.2.3+1.16.2
		gottaclimbfast: Gotta Climb Fast! 1.0
		gravel-ores: Gravel Ores 1.2.0+1.16.2
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		imm_ptl_core: Immersive Portals Core 0.34
		immersive_portals: Immersive Portals 0.34
		inventorypause: Inventory Pause 1.0.3
		inventorysorter: Inventory Sorter 1.7.4-1.16
		jankson: Jankson 3.0.1+j1.2.0
		json-model-extensions: JSON Model Extensions 1.15.124
		kyrptconfig: Kytpt Config 1.1.2-1.16
		lambdabettergrass: LambdaBetterGrass 1.0.1+1.16.3
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.0.0+1.16.3
		lithium: Lithium 0.5.6
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		materialisation: Materialisation 3.0.3
		mcdw: MC Dungeons Weapons 1.1.3
		medievalweapons: Medieval Weapons 1.0.0
		minecraft: Minecraft 1.16.3
		mo_glass: Mo Glass 1.4-MC1.16.3
		modmenu: Mod Menu 1.14.6+build.31
		moenchantments: Mo'Enchantments 1.13.7
		more_gems: More Gems 1.1.4
		morebookshelves: Bookshelving 0.0.0
		morecraftingtables: Oh, How the Crafting Has Tabled! 0.1.3-1.16.3
		mostructures: Mo' Structures 1.0.0-pre3+mc.1.16.2
		moundertweaks: MounderTweaks 1.4.1
		nbtcrafting: NBT Crafting 2.0.0-rc.7+mc1.16.2-pre1
		nookbuild: NookBuild 1.1
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		overpowered_mending: Overpowered Mending 2.2.2
		packed: Packed Storage 1.0.8
		patchouli: Patchouli 1.16.2-44-FABRIC
		phosphor: Phosphor 0.6.0+build.7
		playerabilitylib: Pal 1.2.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		ring_of_attraction: Ring Of Attraction 1.0.23
		ring_of_growth: Ring Of Growth 1.0.21
		ringsofascension: Rings of Ascension 1.0.7
		rotten: FleshZ 1.2.2
		roughlyenoughitems: Roughly Enough Items 5.6.1
		roughlyenoughitems-api: REI (API) 5.6.1
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.6.1
		roughlyenoughitems-runtime: REI (Runtime) 5.6.1
		rpgstats: RPGStats 2.3.2+1.16.3
		shieldisruptor: Shield Disruptor 1.1.1
		silkspawners: SilkSpawners 1.0.0
		simple_backpack: SimpleBackpack 1.0.28
		special-circumstances: Special Circumstances 1.7.206
		spruceui: SpruceUI 1.6.4
		tinytweaks: TinyTweaks 1.0.13
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		tool_action_helper: Tool Action Helper 1.0.1
		torohealth: ToroHealth Damage Indicators 1.16.3-fabric-1
		trinkets: Trinkets 2.6.5
		tweakeroo: Tweakeroo 0.10.0-dev.20200913.175041
		vanillaenhanced: VanillaEnhanced 1.3.0
		xaerominimap: Xaero's Minimap 20.25.1
		xaeroworldmap: Xaero's World Map 1.11.0
	Patchouli open book context: n/a
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GT 650M/PCIe/SSE2 GL version 4.6.0 NVIDIA 411.63, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric/fabric-keybindings-v0, fabric/materialisation, fabric/carvepump, fabric/fabricloader, fabric/trinkets, fabric/adapaxels, fabric/lambdabettergrass, fabric/torohealth, fabric/fabric-game-rule-api-v1, fabric/fabric-api-base, fabric/rpgstats, fabric/shieldisruptor, fabric/xaeroworldmap, fabric/nookbuild, fabric/adabraniummod, fabric/playerabilitylib, fabric/fabric-blockrenderlayer-v1, fabric/morebookshelves, fabric/mo_glass, fabric/simple_backpack, fabric/fabric, fabric/dawn, fabric/fabric-networking-v0, fabric/rotten, fabric/imm_ptl_core, fabric/fabric-screen-handler-api-v1, fabric/modmenu, fabric/fabric-tool-attribute-api-v1, fabric/roughlyenoughitems-runtime, fabric/fabric-crash-report-info-v1, fabric/fabric-events-interaction-v0, fabric/moundertweaks, fabric/mostructures, fabric/curios, fabric/fabric-language-kotlin, fabric/nbtcrafting, fabric/fabric-key-binding-api-v1, fabric/overpowered_mending, fabric/cloth-config2, fabric/fabric-resource-loader-v0, fabric/expandedstorage, fabric/fabric-registry-sync-v0, fabric/vanillaenhanced, fabric/fabric-mining-levels-v0, fabric/cleanview, fabric/fabric-models-v0, fabric/fabric-item-groups-v0, fabric/fabric-renderer-api-v1, fabric/gbfabrictools, fabric/inventorysorter, fabric/libcd, fabric/grindenchantments, fabric/cavebiomes, fabric/moenchantments, fabric/falling_tree, fabric/fabric-containers-v0, fabric/fabric-object-builder-api-v1, fabric/gravel-ores, fabric/ringsofascension, fabric/medievalweapons, fabric/tinytweaks, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-textures-v0, fabric/elytra-recipe, fabric/fabric-rendering-fluids-v1, fabric/fabric-lifecycle-events-v1, fabric/immersive_portals, fabric/fabric-renderer-registries-v1, fabric/fabric-loot-tables-v1, fabric/more_gems, fabric/gottaclimbfast, fabric/fabric-networking-blockentity-v0, fabric/okzoomer, fabric/jankson, fabric/fabric-renderer-indigo, fabric/ring_of_growth, fabric/fabric-item-api-v1, fabric/roughlyenoughitems, fabric/xaerominimap, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/packed, fabric/spruceui, fabric/autoconfig1u, fabric/fabric-content-registries-v0, fabric/fabric-tag-extensions-v0, fabric/fabric-biome-api-v1, fabric/durabilityviewer, fabric/ring_of_attraction, fabric/economical_villager_trading, fabric/byg, fabric/carrier, fabric/fabric-events-lifecycle-v0, fabric/inventorypause, fabric/fabric-object-builders-v0, fabric/bettercaves (incompatible), fabric/malilib (incompatible), fabric/reach-entity-attributes (incompatible), fabric/tweakeroo (incompatible), file/minecraft-dungeons-pack-1-16-2-v3-0.zip, file/Clear+Glass+Pack+1.16.2.zip, lambdabettergrass/default, fabric/adorn, fabric/adventurez, fabric/amecsapi, fabric/backpackmod, fabric/backslot, fabric/canvas, fabric/earthtojavamobs, fabric/fermion, fabric/fermion-orientation, fabric/fermion-varia, fabric/flyring, fabric/frex, fabric/json-model-extensions, fabric/libgui, fabric/lithium, fabric/mcdw, fabric/morecraftingtables, fabric/patchouli (incompatible), file/More+Canvas+Compat-1.1-1.16.2.zip, fabric/phosphor, fabric/special-circumstances, file/Clarity-1.16.zip, fabric/betternether
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\LordBaane\Downloads\mmc-stable-win32\MultiMC\instances\Fabric1\.minecraft\crash-reports\crash-2020-10-15_20.45.54-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.

**Comment by spiralhalo** [comment]
Any steps to reproduce this crash?

From the logs it seems related to fleshz mod. If possible, please confirm with latest version of fleshz in 1.17.

**Comment by spiralhalo** [comment]
Can't reproduce with latest FleshZ for 1.17.
