### ISSUE TITLE
Incompatibility with realistic clouds mod.

### ISSUE THREAD

**Issue by Sirbucket** [grondag/canvas#120]
I don't understand why it crashed, all I know is all the mods I installed said nothing about not being compatible or were listed as compatible.

Actually looking at the logs I suspect it being the realistic clouds mod but I might just be stupid.

Another update, my suspicion was right, it is incompatible with the realistic clouds mod https://www.curseforge.com/minecraft/mc-mods/realisticclouds .
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2020-10-29 21:14:37 EDT
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.class_638.method_29287()Lnet/minecraft/class_5321;
    at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.47)
    at net.minecraft.client.render.WorldRenderer.handler$bbd000$renderClouds(WorldRenderer:7614)
    at net.minecraft.client.render.WorldRenderer.renderClouds(WorldRenderer)
    at grondag.canvas.render.CanvasWorldRenderer.renderWorld(CanvasWorldRenderer.java:773)
    at grondag.canvas.render.CanvasWorldRenderer.render(CanvasWorldRenderer.java:1144)
    at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:727)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:546)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1023)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:656)
    at net.minecraft.client.MinecraftClient.handler$zfl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:679)
    at net.minecraft.client.MinecraftClient.handler$zfl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:679)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  All players: 1 total; [class_746['redacted'/805, l='ClientLevel', x=65.50, y=80.00, z=-32.50]]
  Chunk stats: Client Chunk Cache: 841, 441
  Level dimension: minecraft:overworld
  Level spawn location: World: (55,75,-30), Chunk: (at 7,4,2 in 3,-2; contains blocks 48,0,-32 to 63,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Level time: 2 game time, 2 day time
  Server brand: fabric
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.16.3
  Minecraft Version ID: 1.16.3
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 556695440 bytes (530 MB) / 1509949440 bytes (1440 MB) up to 4294967296 bytes (4096 MB)
  CPUs: 8
  JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Fabric Loader (fabricloader), Canvas Renderer (canvas)
  Fabric Mods: angerable-patch: Angerable Patch 1.0.0-1.16.1
               antighost: AntiGhost 1.16.2-fabric0.17.2-1.1.3
               appleskin: AppleSkin 1.0.11
               autoconfig1u: Auto Config v1 Updated 3.2.2
               better_mod_button: Better Mod Button 1.1.4
               betterf3: BetterF3 1.1.1
               blue_endless_jankson: jankson 1.1.2
               blur: Blur 1.0.6
               canvas: Canvas Renderer 1.0.989
               chunkborders: ChunkBorders 0.4.3
               cleancut: CleanCut mc1.16-2.1-fabric
               clear-skies: Clear Skies 1.5.48
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.5
               cloth-config2: Cloth Config v4 4.8.2
               colormatic: Colormatic 2.2.7+mc.1.16.3
               cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
               crowdin-translate: CrowdinTranslate 1.1
               dynamicfps: Dynamic FPS 1.2.1
               dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
               fabric: Fabric API 0.24.3+build.414-1.16
               fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
               fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a95
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a95
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a95
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
               fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab95
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a95
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a95
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a95
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a95
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
               fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a95
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
               fabricloader: Fabric Loader 0.10.5+build.213
               fabriczero: Fabric Zero 0.1.4
               fastbench: FastBench 2.3
               fastfurnace: FastFurnace 2.3
               fatxporbs: Fat Experience Orbs 0.0.7
               fermion: Fermion 2.6.206
               fermion-orientation: Fermion Orientation 1.1.205
               fermion-varia: Fermion Varia 2.4.206
               fiber: fiber 0.23.0-1
               firstperson: FirstpersonModel 1.3.0
               frex: FREX 3.4.140
               gbfabrictools: GBfabrictools 1.2.2+1.16
               healthoverlay: Health Overlay 3.6.12
               horsestatsvanilla: Horse Stats Vanilla 4.1.4
               itemmodelfix: Item Model Fix 0.2.4
               jankson: Jankson 3.0.1+j1.2.0
               json-model-extensions: JSON Model Extensions 1.15.124
               lambdynlights: LambDynamicLights 1.3.1+1.16.3
               libgui: LibGui 3.0.0+1.16.3
               lithium: Lithium 0.5.6
               loadcatcher: Entrypoint Catcher 2.0.0
               lock_minecart_view: Better minecart rotation 1.2.1
               minecraft: Minecraft 1.16.3
               modmenu: Mod Menu 1.14.6+build.31
               namepain: Name Pain 1.3.0
               nofireoverlay: No Fire Overlay Mod 1.0.0
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               overloadedarmorbar: Overloaded Armor Bar 5.0.0-fabric
               overworld_two: Overworld 2 1.0.3
               petowner: Pet Owner 1.7.0-1.16.2+
               phosphor: Phosphor 0.6.0+build.7
               realisticclouds: RealisticClouds 0.0.2+1.16.1
               roughlyenoughitems: Roughly Enough Items 5.7.0
               roughlyenoughitems-api: REI (API) 5.7.0
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.7.0
               roughlyenoughitems-runtime: REI (Runtime) 5.7.0
               satin: Satin 1.4.1
               smokeextender: Smoke Extender 1.4.0
               special-circumstances: Special Circumstances 1.7.206
               spruceui: SpruceUI 1.6.4
               toggle_entity_render: ToggleEntityRender 1.0.2
               torohealth: ToroHealth Damage Indicators 1.16.3-fabric-1
               xlpackets: XLPackets 1.1
  Launched Version: fabric-loader-0.10.5+build.213-1.16.3
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Graphics mode: fabulous
  Resource Packs: vanilla, fabric/autoconfig1u, fabric/cloth-config2, fabric/fabric, fabric/fabric-api-base, fabric/fabric-biome-api-v1, fabric/fabric-blockrenderlayer-v1, fabric/fabric-containers-v0, fabric/fabric-content-registries-v0, fabric/fabric-crash-report-info-v1, fabric/fabric-events-interaction-v0, fabric/fabric-events-lifecycle-v0, fabric/fabric-game-rule-api-v1, fabric/fabric-item-api-v1, fabric/fabric-item-groups-v0, fabric/fabric-key-binding-api-v1, fabric/fabric-keybindings-v0, fabric/fabric-lifecycle-events-v1, fabric/fabric-loot-tables-v1, fabric/fabric-mining-levels-v0, fabric/fabric-models-v0, fabric/fabric-networking-blockentity-v0, fabric/fabric-networking-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-object-builders-v0, fabric/fabric-registry-sync-v0, fabric/fabric-renderer-api-v1, fabric/fabric-renderer-indigo, fabric/fabric-renderer-registries-v1, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-rendering-fluids-v1, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-resource-loader-v0, fabric/fabric-screen-handler-api-v1, fabric/fabric-tag-extensions-v0, fabric/fabric-textures-v0, fabric/fabric-tool-attribute-api-v1, fabric/fabricloader, fabric/lambdynlights, fabric/lithium, fabric/modmenu, fabric/phosphor, fabric/roughlyenoughitems, fabric/roughlyenoughitems-runtime, fabric/spruceui, fabric/antighost, fabric/appleskin (incompatible), fabric/better_mod_button, fabric/betterf3, fabric/blur, fabric/canvas, fabric/chunkborders, fabric/cleancut, fabric/clear-skies, fabric/colormatic, fabric/dynamicfps, fabric/dynamicsoundfilters, fabric/fabric-command-api-v1, fabric/fabriczero, fabric/fastfurnace, fabric/fermion, fabric/fermion-orientation, fabric/fermion-varia, fabric/firstperson, fabric/frex, fabric/gbfabrictools, fabric/healthoverlay, fabric/horsestatsvanilla, fabric/itemmodelfix, fabric/jankson, fabric/json-model-extensions, fabric/libgui, fabric/lock_minecart_view, fabric/namepain, fabric/nofireoverlay, fabric/notenoughcrashes, fabric/overloadedarmorbar, fabric/overworld_two, fabric/petowner, fabric/satin, fabric/smokeextender, fabric/special-circumstances, fabric/toggle_entity_render, fabric/torohealth, file/VanillaTweaks_r271241.zip
  Current Language: English (US)
  CPU: 8x AMD Ryzen 5 2400G with Radeon Vega Graphics
  Client Crashes Since Restart: 3
  Integrated Server Crashes Since Restart: 0

**Comment by ramidzkh** [comment]
This looks more like you're running a Minecraft version Canvas doesn't support. Please try updating Canvas

**Comment by Sirbucket** [comment]
Oh I did, it had the same issue, this was an old log I forgot to replace with a new crash log, to sum it up it just doesn't support the mod I stated.

**Comment by Sirbucket** [comment]
Actually that's the updated curse version, so no I did upload the right logs.

**Comment by Sirbucket** [comment]
I realized it cause it said something about clouds in the error text, so I uninstalled that mod and it worked.

**Comment by Sirbucket** [comment]
I'd probably label this post as a compatibility error.

**Comment by ramidzkh** [comment]
Can you post your new logs? It might not be reproducible on different hardware

**Comment by Sirbucket** [comment]
Sorry it took a while, was dealing with other things.

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2020-10-29 21:14:37 EDT
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.class_638.method_29287()Lnet/minecraft/class_5321;
    at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.47)
    at net.minecraft.client.render.WorldRenderer.handler$bbd000$renderClouds(WorldRenderer:7614)
    at net.minecraft.client.render.WorldRenderer.renderClouds(WorldRenderer)
    at grondag.canvas.render.CanvasWorldRenderer.renderWorld(CanvasWorldRenderer.java:773)
    at grondag.canvas.render.CanvasWorldRenderer.render(CanvasWorldRenderer.java:1144)
    at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:727)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:546)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1023)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:656)
    at net.minecraft.client.MinecraftClient.handler$zfl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:679)
    at net.minecraft.client.MinecraftClient.handler$zfl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:679)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  All players: 1 total; [class_746['Sirbucket_'/805, l='ClientLevel', x=65.50, y=80.00, z=-32.50]]
  Chunk stats: Client Chunk Cache: 841, 441
  Level dimension: minecraft:overworld
  Level spawn location: World: (55,75,-30), Chunk: (at 7,4,2 in 3,-2; contains blocks 48,0,-32 to 63,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Level time: 2 game time, 2 day time
  Server brand: fabric
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.16.3
  Minecraft Version ID: 1.16.3
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 556695440 bytes (530 MB) / 1509949440 bytes (1440 MB) up to 4294967296 bytes (4096 MB)
  CPUs: 8
  JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Fabric Loader (fabricloader), Canvas Renderer (canvas)
  Fabric Mods: angerable-patch: Angerable Patch 1.0.0-1.16.1
               antighost: AntiGhost 1.16.2-fabric0.17.2-1.1.3
               appleskin: AppleSkin 1.0.11
               autoconfig1u: Auto Config v1 Updated 3.2.2
               better_mod_button: Better Mod Button 1.1.4
               betterf3: BetterF3 1.1.1
               blue_endless_jankson: jankson 1.1.2
               blur: Blur 1.0.6
               canvas: Canvas Renderer 1.0.989
               chunkborders: ChunkBorders 0.4.3
               cleancut: CleanCut mc1.16-2.1-fabric
               clear-skies: Clear Skies 1.5.48
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.5
               cloth-config2: Cloth Config v4 4.8.2
               colormatic: Colormatic 2.2.7+mc.1.16.3
               cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
               crowdin-translate: CrowdinTranslate 1.1
               dynamicfps: Dynamic FPS 1.2.1
               dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
               fabric: Fabric API 0.24.3+build.414-1.16
               fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
               fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a95
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a95
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a95
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
               fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab95
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a95
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a95
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a95
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a95
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
               fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a95
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
               fabricloader: Fabric Loader 0.10.5+build.213
               fabriczero: Fabric Zero 0.1.4
               fastbench: FastBench 2.3
               fastfurnace: FastFurnace 2.3
               fatxporbs: Fat Experience Orbs 0.0.7
               fermion: Fermion 2.6.206
               fermion-orientation: Fermion Orientation 1.1.205
               fermion-varia: Fermion Varia 2.4.206
               fiber: fiber 0.23.0-1
               firstperson: FirstpersonModel 1.3.0
               frex: FREX 3.4.140
               gbfabrictools: GBfabrictools 1.2.2+1.16
               healthoverlay: Health Overlay 3.6.12
               horsestatsvanilla: Horse Stats Vanilla 4.1.4
               itemmodelfix: Item Model Fix 0.2.4
               jankson: Jankson 3.0.1+j1.2.0
               json-model-extensions: JSON Model Extensions 1.15.124
               lambdynlights: LambDynamicLights 1.3.1+1.16.3
               libgui: LibGui 3.0.0+1.16.3
               lithium: Lithium 0.5.6
               loadcatcher: Entrypoint Catcher 2.0.0
               lock_minecart_view: Better minecart rotation 1.2.1
               minecraft: Minecraft 1.16.3
               modmenu: Mod Menu 1.14.6+build.31
               namepain: Name Pain 1.3.0
               nofireoverlay: No Fire Overlay Mod 1.0.0
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               overloadedarmorbar: Overloaded Armor Bar 5.0.0-fabric
               overworld_two: Overworld 2 1.0.3
               petowner: Pet Owner 1.7.0-1.16.2+
               phosphor: Phosphor 0.6.0+build.7
               realisticclouds: RealisticClouds 0.0.2+1.16.1
               roughlyenoughitems: Roughly Enough Items 5.7.0
               roughlyenoughitems-api: REI (API) 5.7.0
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.7.0
               roughlyenoughitems-runtime: REI (Runtime) 5.7.0
               satin: Satin 1.4.1
               smokeextender: Smoke Extender 1.4.0
               special-circumstances: Special Circumstances 1.7.206
               spruceui: SpruceUI 1.6.4
               toggle_entity_render: ToggleEntityRender 1.0.2
               torohealth: ToroHealth Damage Indicators 1.16.3-fabric-1
               xlpackets: XLPackets 1.1
  Launched Version: fabric-loader-0.10.5+build.213-1.16.3
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Graphics mode: fabulous
  Resource Packs: vanilla, fabric/autoconfig1u, fabric/cloth-config2, fabric/fabric, fabric/fabric-api-base, fabric/fabric-biome-api-v1, fabric/fabric-blockrenderlayer-v1, fabric/fabric-containers-v0, fabric/fabric-content-registries-v0, fabric/fabric-crash-report-info-v1, fabric/fabric-events-interaction-v0, fabric/fabric-events-lifecycle-v0, fabric/fabric-game-rule-api-v1, fabric/fabric-item-api-v1, fabric/fabric-item-groups-v0, fabric/fabric-key-binding-api-v1, fabric/fabric-keybindings-v0, fabric/fabric-lifecycle-events-v1, fabric/fabric-loot-tables-v1, fabric/fabric-mining-levels-v0, fabric/fabric-models-v0, fabric/fabric-networking-blockentity-v0, fabric/fabric-networking-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-object-builders-v0, fabric/fabric-registry-sync-v0, fabric/fabric-renderer-api-v1, fabric/fabric-renderer-indigo, fabric/fabric-renderer-registries-v1, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-rendering-fluids-v1, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-resource-loader-v0, fabric/fabric-screen-handler-api-v1, fabric/fabric-tag-extensions-v0, fabric/fabric-textures-v0, fabric/fabric-tool-attribute-api-v1, fabric/fabricloader, fabric/lambdynlights, fabric/lithium, fabric/modmenu, fabric/phosphor, fabric/roughlyenoughitems, fabric/roughlyenoughitems-runtime, fabric/spruceui, fabric/antighost, fabric/appleskin (incompatible), fabric/better_mod_button, fabric/betterf3, fabric/blur, fabric/canvas, fabric/chunkborders, fabric/cleancut, fabric/clear-skies, fabric/colormatic, fabric/dynamicfps, fabric/dynamicsoundfilters, fabric/fabric-command-api-v1, fabric/fabriczero, fabric/fastfurnace, fabric/fermion, fabric/fermion-orientation, fabric/fermion-varia, fabric/firstperson, fabric/frex, fabric/gbfabrictools, fabric/healthoverlay, fabric/horsestatsvanilla, fabric/itemmodelfix, fabric/jankson, fabric/json-model-extensions, fabric/libgui, fabric/lock_minecart_view, fabric/namepain, fabric/nofireoverlay, fabric/notenoughcrashes, fabric/overloadedarmorbar, fabric/overworld_two, fabric/petowner, fabric/satin, fabric/smokeextender, fabric/special-circumstances, fabric/toggle_entity_render, fabric/torohealth, file/VanillaTweaks_r271241.zip
  Current Language: English (US)
  CPU: 8x AMD Ryzen 5 2400G with Radeon Vega Graphics
  Client Crashes Since Restart: 3
  Integrated Server Crashes Since Restart: 0

These were the logs as of the crash, I'll try to redproduce it again with only canvas and that mod installed on the most recent canvas and realistic clouds mod version.

**Comment by Sirbucket** [comment]
I didn't get a crash report this time around, whatever changed this time around with either canvas, the fabric api, or realistic clouds has been fixed, either me or you can close it but I'd like to know if you have any other comments on it.

**Comment by Sirbucket** [comment]
IE It's fixed
