### ISSUE TITLE
items and menues disappear depending on where you look at

### ISSUE THREAD

**Issue by mer-at** [grondag/canvas#123]
basically the items in the item bar disappear depending on where i look at.
also when the item symbols have disappeared, also all menues are invisible (e.g. inventory, esc menu)
i've uploaded a video of that to youtube: https://youtu.be/pOX9DZip78Y

i also tried to delete all other mods, basically only using canvas render: https://imgur.com/a/QFCVxcT

also it happens with multiple older versions of canvas render as well.

**Comment by Neubulae** [comment]
4th report of such issue. Peculiar indeed

**Comment by marchofiron** [comment]
happens to me too.

**Comment by grondag** [comment]
Is this still happening in latest build?  A fix a few days back addressed a problem like this.

**Comment by eristhea** [comment]
This issue is gone on the latest builds for me.

**Comment by mer-at** [comment]
issue is also gone for me
