### ISSUE TITLE
Disabling fog breaks blindness status effect

### ISSUE THREAD

**Issue by spiralhalo** [grondag/canvas#125]
The blindness status works by lowering fog distance. Disabling fog entirely allows the player to see normally.

Fog "vanilla":
![image](https://user-images.githubusercontent.com/8444172/98584589-a925e980-22f8-11eb-8270-1fc771a4051c.png)

Fog "subtle":
![image](https://user-images.githubusercontent.com/8444172/98584671-cf4b8980-22f8-11eb-8a7a-18abc0368a5b.png)

Fog "none":
![image](https://user-images.githubusercontent.com/8444172/98584551-9ca19100-22f8-11eb-927f-9035e281a3bb.png)

Tested on 1.0.1095-snapshot

**Comment by Kichura** [comment]
Tried reproducing this fog issue and sure enough the problem is present, However this also applies to sodium (See image) and other mods that make use of the fog removal check.
![image](https://user-images.githubusercontent.com/68134602/102701637-427ddf00-4259-11eb-9787-1639d3261c4e.png)

**Comment by grondag** [comment]
Oh, I see.  This is probably an easy fix.  I'll have a look.

**Comment by grondag** [comment]
I'd like to add more granular control of fog later, but this is at least better for now.
