### ISSUE TITLE
crashes when i join a server with colormatic alongside canvas

### ISSUE THREAD

**Issue by arceuss** [grondag/canvas#127]
[https://paste.ee/p/TVpjO](https://paste.ee/p/TVpjO) log here

**Comment by spiralhalo** [comment]
Ah, seems that the log expired.

I can't reproduce this crash in either multiplayer server (vanilla, papermc) and single player world. Using Canvas 1.0.1236 and Colormatic 2.2.7+mc.1.16.3. Using Jicklus resource pack (seems to support OF colors).

What version of Canvas are you using? Does it only crash with a specific resource pack?

**Comment by spiralhalo** [comment]
Gonna close it until it can be confirmed reproducible.
