### ISSUE TITLE
Inventory doesnt render correctly

### ISSUE THREAD

**Issue by Shyrogan** [grondag/canvas#131]
The inventory is sometimes weirdly placed:
![2020-11-14_16 08 10](https://user-images.githubusercontent.com/24733746/99150297-bf82cb00-2693-11eb-8600-24418f419770.png)

This screenshot was taken in a Fabric workspace, the mod is simply added with: `modCompile "grondag:canvas-mc116:1.0.+"`
I can provide specific logs if asked.

**Comment by grondag** [comment]
I believe this was fixed a while back.  Please reopen if able to reproduce in the latest GitHub build.
