### ISSUE TITLE
Canvas Crash when opening chest

### ISSUE THREAD

**Issue by campbebj** [grondag/canvas#147]
Chest contents were: Saplings, Seeds, Grass, Torches (found it in a village)

i didnt see any errors, but as soon as i removed Canvas mod it started working again.

let me know if you need me to do anything else to reproduce. (or if you can tell me how to get you logs, becaues nothing showed up in the standard logs)

**Comment by grondag** [comment]
Would need a log to even know what to look at.  Opening chests works fine normally.  Please reopen if able to reproduce reliably and provide a log.
