### ISSUE TITLE
Prevents the game from launching

### ISSUE THREAD

**Issue by Dakedres** [grondag/canvas#15]
When Canvas is installed my game won't launch

Fabric Version: fabric-loader-0.4.7+build.147-1.14-build.10
Java Version: Java 8 (jre8-openjdk)
Operating System: Arch Linux

This is all that's found in the `latest.log`:
```
[01:26:20] [main/INFO]: Loading for game Minecraft 1.14.1
```

Thank you for your time

**Comment by grondag** [comment]
Hi Drakedres - thank you for giving Canvas a try.

Canvas 0.6 needs Minecraft 1.14.2 prerelease and [Fabric API 0.3.0 build 165](https://minecraft.curseforge.com/projects/fabric/files/2713346) or later. 

I know it's listed on CF as Minecraft 1.14.1 - unfortunately there is not yet a category for 1.14.2. I regret the confusion.

Going to close the issue, but feel welcome to reopen if that doesn't resolve your problem.
