### ISSUE TITLE
[Suggestion] Particle culling

### ISSUE THREAD

**Issue by Leo40Git** [grondag/canvas#150]
Couldn't see any code relating to it in [`CanvasParticleRenderer`](https://github.com/grondag/canvas/blob/one/src/main/java/grondag/canvas/render/CanvasParticleRenderer.java).

**Comment by supsm** [comment]
Canvas doesn't have particle culling yet, but you can add a separate mod if you want it: https://www.curseforge.com/minecraft/mc-mods/cull-particles-fabric

**Comment by Leo40Git** [comment]
Canvas overwrites the code that mod patches to add culling.

**Comment by supsm** [comment]
oh... I didn't know that
