### ISSUE TITLE
Possible issue with night vision

### ISSUE THREAD

**Issue by Alpha-Flyte** [grondag/canvas#153]
Issue: Applying night vision in dark areas turns everything dark rather than bright

How to replicate: Use any night vision inducing item, or simply add effect through commands. Screen turns black as if blindness had been applied

Details: Running Minecraft 1.16.3 Fabric, Using latest compatible Curseforge ver. of Canvas Renderer, 3rd party Mod Compat for Canvas

**Comment by AtlasTheProto** [comment]
[Cannot replicate on latest github build 1191](http://protogen.ga/p/6k6DRGGAab.mp4)

**Comment by Alpha-Flyte** [comment]
Hmm, perhaps this is a mod conflict....

The things that applied night vision that weren't working were:
Extra Alchemy's Potion Rings
Origins' Feline Origin Inherent Night Vision Perk
Artifacts' Night Vision Goggles

I have Lithium, Phosphor, and Lamb Dynamic Lights, but those shouldn't be conflicting with Canvas

My sneaking suspicion is that its an issue with flickering night vision effects when it's about to end, but I'm not an expert so I wouldn't know for sure

**Comment by grondag** [comment]
Unable to duplicate in the latest GitHub builds.  Please reopen if able to reproduce reliably.
