### ISSUE TITLE
Carpet mod particles aren't rendered

### ISSUE THREAD

**Issue by supsm** [grondag/canvas#154]
Expected (sodium): 
![2020-12-10_10 55 49](https://user-images.githubusercontent.com/60897356/101817171-d839a180-3ad6-11eb-8ee8-01a01d77a72f.png)

Canvas: 
![2020-12-10_10 58 49](https://user-images.githubusercontent.com/60897356/101817213-e8518100-3ad6-11eb-8e91-43eea41c26d9.png)

**Comment by ramidzkh** [comment]
This was fixed long ago on carpet's side
