### ISSUE TITLE
[compatibility] game crashes when loading the end dimension with the BetterEnd mod enabeled

### ISSUE THREAD

**Issue by julius-te** [grondag/canvas#167]

**Comment by spiralhalo** [comment]
What version of Canvas? Can you provide logs or crash report?

Also I personally couldn't reproduce it with better-end-0.8.0-beta and canvas-mc116-1.0.1237

**Comment by grondag** [comment]
Also unable to reproduce with better-end-0.8.0-beta and canvas build 1241.  Please reopen if recurs.

**Comment by julius-te** [comment]
I have not noticed that the version i was using was made for 1.16.3 because I have not had any issues with it besides this with 1.16.4. The new version (that was made for 1.16.4) that came out a couple hours also made it work for me. I am very sorry I wasted your time.
