### ISSUE TITLE
Handheld lighting follows camera, not the player

### ISSUE THREAD

**Issue by ghost** [grondag/canvas#169]
![2020-12-19_08 30 17](https://user-images.githubusercontent.com/35193331/102675590-f1c4a280-41d4-11eb-85df-8bf08947e35b.png)
Canvas Version: 1.0.1241
Minecraft Version: 1.16.4
Fabric API Version: 0.28.3

**Comment by grondag** [comment]
This is known limitation of the current implementation.   It does it this way because it is insanely cheap and simple.

More sophisticated dynamic lights will be added in the future, but for now this is how it works.
