### ISSUE TITLE
Canvas not playing "nice" with Curios 0.0.10-1.16.3 for Fabric.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [grondag/canvas#172]
Just a heads up. Using the latest version on Canvas with Curios for Fabric causes black screen and invisible inventory items. Trinkets works, but not curios.

Doesn't crash just doesn't render stuff.

**Comment by spiralhalo** [comment]
> Using the latest version

Please specify what version when reporting issues.

And as Canvas development has stopped in 1.16, this issue seems irrelevant to the current development efforts. Curios is succeeded by Trinkets API in 1.17 it seems.
