### ISSUE TITLE
Player model lit incorrectly in GUI

### ISSUE THREAD

**Issue by linzexin022** [grondag/canvas#173]
(Picture updated)
![103214349-24943680-494b-11eb-977a-636ba9fbc878](https://user-images.githubusercontent.com/59003232/103450507-9fb26f80-4cf2-11eb-9487-c45014b94015.png)

Minecraft version: 1.16.4
Canvas version: 1.0.1257

**Comment by linzexin022** [comment]
Another light source bug:
![Vanilla vs Canvas](https://user-images.githubusercontent.com/59003232/103214885-aa64b180-494c-11eb-889d-d1fe31eb9cc2.png)

**Comment by grondag** [comment]
The difference in beacon rendering is intentional.  Player model lighting is not.

**Comment by linzexin022** [comment]
Sorry for the wrong marking of the first picture

**Comment by supsm** [comment]
cannot reproduce in latest canvas
