### ISSUE TITLE
Crash during restart of resource packs

### ISSUE THREAD

**Issue by ghost** [grondag/canvas#175]
[hs_err_pid11784.log](https://github.com/grondag/canvas/files/5751808/hs_err_pid11784.log)

The game crashes only when I have set the game detail level 0-1. At detail level 2-4, the game stops crashing when reloading resource packs

**Comment by spiralhalo** [comment]
By "detail level" did you mean mipmap level? In that case I can't seem to reproduce it in a recent build (commit 74ffaf8d6e287e03185eaf214d57606422b9a014).

If this is related to #70, it appears to be fixed.

Feel free to reopen if it persists in latest build.
