### ISSUE TITLE
Crash with latest Fabric API

### ISSUE THREAD

**Issue by Li-Liu** [grondag/canvas#177]
Minecraft crashes before reaching the main menu when the current version of **Canvas (1.0.1257)**  is used alongside the latest version of the **Fabric API (0.29.0)**, producing the following crash report:

[crash-2020-12-30_18.30.56-client.txt](https://github.com/grondag/canvas/files/5756697/crash-2020-12-30_18.30.56-client.txt)

**Comment by Li-Liu** [comment]
A new crash occurs now that **Canvas** has been updated, using latest **Fabric API**:

[crash-2020-12-31_15.13.11-client.txt](https://github.com/grondag/canvas/files/5758447/crash-2020-12-31_15.13.11-client.txt)

**Comment by grondag** [comment]
The build 1263 file posted to Curseforge was missing dependencies. A corrected build as been uploaded and should be available for download shortly.  It can also be found here: https://github.com/grondag/canvas/releases/download/1.0.1263-unstable/canvas-mc116-1.0.1263.jar
