### ISSUE TITLE
Crash sometimes when breaking blocks

### ISSUE THREAD

**Issue by juliand665** [grondag/canvas#18]
This has happened twice so far, upon breaking a block, the game will sometimes crash. The first time around, it even threw an unreported exception; this time, it's reported: 
[latest.log](https://github.com/grondag/canvas/files/3203792/latest.log)

Versions are probably evident from that log, but otherwise:
- Fabric 1.14.2 Pre-Release 2+build.5
- Fabric Loader 0.4.7+build.147
- Fabric API 0.3.0-pre+build.165
- Canvas 0.6.50

**Comment by grondag** [comment]
Thank you for the crash log. Very helpful. Somehow the cached world data for chunk rebuilds is leaking into block breaking. Will fix.
