### ISSUE TITLE
Issues/Crashes when changing Render Distance in-game

### ISSUE THREAD

**Issue by fulcray** [grondag/canvas#181]
When changing the render distance from the minecraft video options with the slider, the log entry `[main/INFO]: Canvas Renderer is initializing.` is logged a few dozen times per second, even when just changing from 10 to 11, for example. Sometimes the following error is given in the console (game keeps running here):
https://pastebin.com/2u9XLgGp

Additionally, a full crash can be reliably produced by starting a new world at a certain view distance, e.g. 10, then immediately going into the options and increasing the view distance, e.g. to 20, while the world is still being built:
https://pastebin.com/WZEukShL
[hs_err_pid6420.log](https://github.com/grondag/canvas/files/5759008/hs_err_pid6420.log)

**Comment by spiralhalo** [comment]
This issue seems old. Feel free to reopen if it persists in latest build of Canvas and state the Canvas version when/if you do.
