### ISSUE TITLE
[Crash] on startup, probably because of FAPI version

### ISSUE THREAD

**Issue by supersaiyansubtlety** [grondag/canvas#184]
Looks like `canvas-mc116-1.0.1267` needs a newer FAPI version than my `fabric-api-0.25.7+1.16`.
If that's the case could you please change the FAPI dependency in `fabric.mod.json` to require the correct minimum FAPI version?

[crash report](https://pastebin.com/72uwMGPi)

**Comment by Kichura** [comment]
Confirmed on this unit as the world rendering event does not seem to work properly.

**Comment by grondag** [comment]
1267 requires FAPI 0.29 or later. It has no new features - its main purpose is to support the newer Fabric version and mods that depend on it.  That said, subsequent versions will also require FAPI v0.29+.

I will try to remember to mark future builds as requiring a specific minimum Fabric version.
