### ISSUE TITLE
Slow culling(?)

### ISSUE THREAD

**Issue by The-PPWD** [grondag/canvas#185]
When rounding an object, there appears to be a delay between when a region of blocks should be visible and when they are actually rendered. It is possible to position the player in a way that keeps these regions from ever being rendered. And only when moving the player so that that region moves further into the view does that region render.

I am using Lumi Lights in the screenshots, but it occurs with the Canvas shaders also.

![2021-01-03_20 06 32](https://user-images.githubusercontent.com/47865452/103497110-1ab87a80-4e06-11eb-88cc-f44ba804cccb.png)
![2021-01-03_20 06 42](https://user-images.githubusercontent.com/47865452/103497112-1c823e00-4e06-11eb-8fec-72553b071953.png)

**Comment by spiralhalo** [comment]
Gonna pitch in my video as well for reference (link to Grondag's discord)

https://discord.com/channels/614624415631671316/614625541114298397/791672287401082911

**Comment by grondag** [comment]
Thanks for the report. This is a bug and will get fixed.

**Comment by mrgrim** [comment]
I'm not sure if it helps, but I recently built a new computer and began experiencing this issue. Previously I was on a Haswell Xeon and GTX 1080 Ti using Windows 7, and I never noticed this. Now I'm on a Ryzen 5950x and a Radeon 6900xt using Windows 10, and it's very noticeable. It becomes very bad when looking out windows of structures.
![2021-05-13_15 25 16](https://user-images.githubusercontent.com/130033/118176514-81c2ed00-b3ff-11eb-8deb-9c69cd59923d.png)

**Comment by spiralhalo** [comment]
Related PR: #241

(is a dirty fix and don't fix every culling problems)

**Comment by grondag** [comment]
Will be fixed in next release, similar to the fix proposed in #241
