### ISSUE TITLE
Enchantment glint weirdness

### ISSUE THREAD

**Issue by supsm** [grondag/canvas#187]
Enchantment glints are kinda weird in the pipeline version of canvas. Sometimes there will be z-fighting, and other times it will simply not appear.

In the inventory player paper doll thing, the player has enchantments, but there is z-fighting. This also happens to handheld items in third person, and dropped items.

Items in the inventory do not appear to have enchantments at all. This also applies to armor that the player is wearing when viewed in third person. However, handheld items do have z-fighting enchantment glints.

![image](https://user-images.githubusercontent.com/60897356/103598727-32503b80-4eb8-11eb-816b-d54d43695d8a.png)
![2021-01-04_18 07 07](https://user-images.githubusercontent.com/60897356/103598739-3c723a00-4eb8-11eb-81f6-427093ed4ffe.png)
![2021-01-04_18 09 52](https://user-images.githubusercontent.com/60897356/103598741-3d0ad080-4eb8-11eb-828a-7633d9777103.png)

**Comment by grondag** [comment]
Glint has been completely redone.
