### ISSUE TITLE
The world has no light whatsoever when Canvas is Installed.

### ISSUE THREAD

**Issue by doctor-something5000** [grondag/canvas#196]
The world when loaded has no light at all when Canvas is installed. However, without Canvas, the lighting is fine.
[Screenshot](https://imgur.com/a/OxPxlYn)

**Comment by ramidzkh** [comment]
What shaderpack(s) and mods?

**Comment by Reeses-Puffs** [comment]
yeah, you need to provide much more information than just "it looks black"

**Comment by doctor-something5000** [comment]
I have the following mods

**Comment by doctor-something5000** [comment]
https://drive.google.com/file/d/1lt0M5ECMQdSe0Q8I3GPfq-PkgxrfCyAh/view?usp=sharing

**Comment by spiralhalo** [comment]
That is a rar file. You should get a mod list from the logs. And bugs should be reproducible with only Canvas unless it's clearly marked as incompatibility with a specific mod.

Also, the issue is unclear from just that image. Can you confirm if this is related to #264 ?
