### ISSUE TITLE
Canvas causes LightOverlay to not work properly

### ISSUE THREAD

**Issue by UpcraftLP** [grondag/canvas#199]
When Canvas is installed together with LightOverlay, the light overlay is only shown along the Z axis.
see https://github.com/shedaniel/LightOverlay/issues/76 for further details.

![image](https://user-images.githubusercontent.com/10714589/105570483-fb987300-5d49-11eb-99c4-dee18e57d2eb.png)

**Comment by supsm** [comment]
I use light overlay with canvas as well, and I've never encountered an issue. It might be an incompatibility with another mod?

**Comment by saltyseadoggo** [comment]
Adding Canvas to the latest version of All of Fabric 3 causes none of Light Overlay's crosses to appear at all when it is enabled.

**Comment by supsm** [comment]
I've experienced this issue before as well, but removing aof solves the issue

**Comment by saltyseadoggo** [comment]
'Removing AoF?' So... removing the entire modpack...? Surely, you can see why that is not very ideal, when removing Canvas is much simpler and doesn't involve depriving oneself of all of these other mods' content?

**Comment by supsm** [comment]
I'm just pointing out it's an incompatibility with another mod, as I said above.

**Comment by dandin87** [comment]
And which mod is that? Its nice that you think its AoF, or rather a mod in AoF, but that it definitely false. As far as I am aware Light Level Overlay has not worked with Canvas in a very long time. In fact Loading the latest canvas for 1.16.5 and latest Light Level Overlay and all its dependencies, FAPI and nothing else, proves that it still does not work. I don't even see a render overlay. 
Modlist
architectury-1.12.148-fabric.jar
canvas-mc116-configurable-pipeline-1.0.1492.jar
cloth-config-4.11.19-fabric.jar
fabric-api-0.32.5+1.16.jar
light-overlay-5.8.1.jar

**Comment by supsm** [comment]
I'm just saying that since I have definitely played with canvas and light overlay, and it has worked for me. This was a few months ago, so something might've changed.

**Comment by supsm** [comment]
Nevermind, just tested it and it still works.

Mods: 
![image](https://user-images.githubusercontent.com/60897356/117092652-bc4bcc00-ad13-11eb-9c97-74d3fb3ab89d.png)
![image](https://user-images.githubusercontent.com/60897356/117092657-be158f80-ad13-11eb-90a2-a743f030614e.png)



![image](https://user-images.githubusercontent.com/60897356/117092572-86a6e300-ad13-11eb-8613-fbbca390249a.png)

**Comment by gniftygnome** [comment]
FYI, this defect remains with Canvas mc116-1.0.1511 and Light Overlay 5.8.1.  Light Overlay 5.5.4 still works fine with the new Canvas version.

**Comment by spiralhalo** [comment]
> FYI, this defect remains with Canvas mc116-1.0.1511 and Light Overlay 5.8.1. Light Overlay 5.5.4 still works fine with the new Canvas version.

I take it the issue is from Light Overlay side?

**Comment by spiralhalo** [comment]
Can confirm in 1.17, except the light overlay isn't showing at all.

Using mods
```
  [✔️] architectury-2.0.16-fabric
  [✔️] canvas-mc117-1.17-1.0.1655
  [✔️] fabric-api-0.34.8+1.17
  [✔️] light-overlay-6.0.0-fabric
```

Using Canvas Standard pipeline.

Logs: https://gist.github.com/spiralhalo/7769a1d36783acf8b99d2504b97ddacd

**Comment by spiralhalo** [comment]
> Can confirm in 1.17, except the light overlay isn't showing at all.

I might have misinterpreted the report. Can confirm that is does show along X = -1 (block pos).

**Comment by spiralhalo** [comment]
I have figured out the issue. LightOverlay uses accesswidener to access and compute frustum visibility directly.

To fix this in our side would require some superfluous computation in the render thread so I find it unlikely but would have to ask Grondag to be sure.

An easier solution is to ask LightOverlay to use the public function `Frustum.isVisible(Box)` to compute visibility as intended.

**Comment by gniftygnome** [comment]
Glad to see some progress on this.  I've linked your comment into the LightOverlay ticket:
https://github.com/shedaniel/LightOverlay/issues/76#issuecomment-874547578

**Comment by spiralhalo** [comment]
Thanks for the wait. It should be fixed now.
