### ISSUE TITLE
Undeclared dependencies

### ISSUE THREAD

**Issue by sargunv** [grondag/canvas#2]
I installed the required dependencies listen on CF (Canvas, Fabric API, Cloth Config, Auto Config, and FREX), but looks like the mod expects ModMenu to be installed too: https://paste.ee/p/QB8kG

After installing ModMenu, now the mod expects Jankson to come from somewhere: https://paste.ee/p/ddAPN. That should probably be shaded.

Installed the rest of my mod list and I guess something provided Jankson because it's no longer having that error, but now it can't find java.nio.Bits.copyFromArray: https://paste.ee/p/GCFmK. I'm on OpenJDK 11, does this depend on a newer version?

**Comment by grondag** [comment]
Thank you for the detailed bug report. 

Version 0.6.42, just uploaded to curseforge should address these issues.  It bundles all necessary dependencies except Fabric API and Fabric Loader.  It does however require a very recent Fabric build. 

If you don't want to wait for approval you can instead grab the build off my maven: https://grondag-repo.appspot.com/grondag/canvas/0.6.42/canvas-0.6.42.jar   Enter `guest` as ID, no password.
