### ISSUE TITLE
Crash when joining world with Colormatic

### ISSUE THREAD

**Issue by helpimnotdrowning** [grondag/canvas#202]
Game crashes when joining any world with Canvas and Colormatic `Tesselating block in world - Canvas Renderer`
[Log](https://paste.ee/p/uZIZa)

The world will get to load the void and load the player hand before crashing out.

System:
Minecraft : 1.16.4
Fabric : 0.11.1
Fabric API : 0.29.3
Canvas : 1.0.1267
Colormatic : 2.2.8
Java : AdoptOpekJDK 11.0.9
OS : Windows 10 2009/20H2 x64

**Comment by spiralhalo** [comment]
Thank you for your report. Development on 1.16 has stopped and as Colormatic isn't yet on 1.17 I will close this issue. Feel free to reopen when it updates.
