### ISSUE TITLE
Held item lighting doesn't work when the player is standing in water

### ISSUE THREAD

**Issue by Sollace** [grondag/canvas#205]
Version: Canvas-mc116-1.0.1267
Mc: 1.16.4 (dev environment)
Fabric: 0.30.0+1.16
Loader: 0.10.6+build.214
No other mods are included that mess with rendering

As the title says. 

A
![image](https://user-images.githubusercontent.com/6429283/107488516-21b67380-6b90-11eb-92e1-5d008c547876.png)

vs

B
![image](https://user-images.githubusercontent.com/6429283/107488572-33981680-6b90-11eb-8010-bf4fb4542bc5.png)

I'm standing in roughtly the same spot, just a little further back so I'm not touching the water. If I step into the water, though, the light goes out.

**Comment by Sollace** [comment]
I'll also note that the default lighting radius is way too big. It's almost twice as far as a place torch would be.

Placed:
![image](https://user-images.githubusercontent.com/6429283/107488797-883b9180-6b90-11eb-8533-992519f47bd4.png)

Held:
![image](https://user-images.githubusercontent.com/6429283/107488847-9b4e6180-6b90-11eb-94a4-199fba4f859f.png)

**Comment by grondag** [comment]
Fixed in https://github.com/grondag/canvas/commit/88d45087f612665e65fccee54156509a84078abc
