### ISSUE TITLE
Entity Culling is sporadic and inconsistent

### ISSUE THREAD

**Issue by Sollace** [grondag/canvas#206]
Version: Canvas-mc116-1.0.1267
Mc: 1.16.4 (dev environment)
Fabric: 0.30.0+1.16
Loader: 0.10.6+build.214
No other mods are included that mess with rendering

Same as chunk rendering, entities don't seem to render unless you're looking directly at them (and sometimes not even then). This issue is present regardless of whether "more accurate entity culling" is turned on or off.

![image](https://user-images.githubusercontent.com/6429283/107489172-fda76200-6b90-11eb-9894-edbec06b1ea7.png)
![image](https://user-images.githubusercontent.com/6429283/107489350-30515a80-6b91-11eb-9012-085be5cb938c.png)
![image](https://user-images.githubusercontent.com/6429283/107489401-3d6e4980-6b91-11eb-8126-11d05a76c46a.png)

**Comment by grondag** [comment]
Entity culling relies on render region culling, so whatever is causing that problem is likely the same.  Still need more information on the environment.  This does not occur when I run Canvas along with latest API/Loader.

**Comment by grondag** [comment]
Closing absent more info.  Please reopen if/when steps to reproduce are known.
