### ISSUE TITLE
[Incompatibility] Physics Mod

### ISSUE THREAD

**Issue by Zentheon** [grondag/canvas#209]
The rendering of physics mod particles is broken entirely by canvas (the latest build of main).  
https://github.com/haubna/PhysicsMod

The mod is apparently closed-source, so I'll be opening an issue on their end as well about it. Donno if there's much to be done about it otherwise.

**Comment by Dolphin2Point1** [comment]
I doubt this will be fixed since the mod is closed source so we can't see how to fix it. Also this mod is just buggy and laggy in general, and shadows libgdx into its jar file.

**Comment by IMS212** [comment]
IrisShaders/Iris#102 also has some form of this issue, seems like Physics Mod in general does weird rendering.

**Comment by Zentheon** [comment]
Which kinda sucks since it seems like the dev of the mod has no interest in supporting the mod any further. I won't close this for now just in case someone else reports the same thing, but someone else can totally close it.

**Comment by grondag** [comment]
Closing for now.  If the mod is revived and becomes supported may revisit.
