### ISSUE TITLE
Above the world height limit, the models become invisible

### ISSUE THREAD

**Issue by SekoiaTree** [grondag/canvas#215]
Any models that get put above the height limit instantly disappear. It happens for any vertices, as long as the entity is above 256 (including debug stuff like hitboxes).

https://streamable.com/e/a1ef8w

**Comment by UltraBlackLinux** [comment]
This is :mojank: afaik

**Comment by SekoiaTree** [comment]
It doesn't happen in vanilla, so it's defo caused by canvas

**Comment by spiralhalo** [comment]
This should be fixed in https://github.com/grondag/canvas/commit/3d4c6d07dcecd84e9b503ca8e777ecbce5617464

https://github.com/grondag/canvas/blob/3d4c6d07dcecd84e9b503ca8e777ecbce5617464/src/main/java/grondag/canvas/render/frustum/RegionCullingFrustum.java#L51-L57
