### ISSUE TITLE
Z-fighting with Iron Chests mod

### ISSUE THREAD

**Issue by cheshyrp** [grondag/canvas#216]
Canvas causes Iron Chests (the Fabric version) to flicker badly as it simultaneously displays the open and closed models.

**Comment by spiralhalo** [comment]
So is the issue simple z-fighting or simultaneously displaying open and closed models? I think z-fighting happens with normal chest too but not as bad as described here.

Also iron chests isn't available yet for 1.17 which is the current primary version for Canvas development. Please reopen when it updates and the issue persists.

**Comment by cheshyrp** [comment]
It's exactly as I described above, simultaneously displaying the open and closed models when any of your chests are open. Unfortunately, I won't be able to test it for you, as I've moved on. I realize that life happens, but ssues need to be addressed much faster than three months if you expect user feedback.
