### ISSUE TITLE
Handheld objects lighting not taking dynamic lighting into account

### ISSUE THREAD

**Issue by jepotter1-archive** [grondag/canvas#218]
See here:

![2021-03-11_17 09 47](https://user-images.githubusercontent.com/20506149/110876629-bba33600-828c-11eb-9a49-96b4ef1c6a01.png)

The torch and pickaxe are black because it thinks there is no light, since there is no light source, just the light coming from the torch itself as dynamic lighting is turned on.

I apologize if I am using insufficiently technical language, I know very little about graphics and game development.

**Comment by spiralhalo** [comment]
Need to confirm this issue in the latest 1.17 build.

**Comment by spiralhalo** [comment]
Can confirm this with Canvas Standard in Canvas 1.0.1690. Seems like a pipeline shader bug.

![image](https://user-images.githubusercontent.com/8444172/124381187-4b149f00-dceb-11eb-8733-9ad60586173a.png)

**Comment by jepotter1-archive** [comment]
Yay! 🎉
