### ISSUE TITLE
A ton of clientside mods cause items to become invisible alongside Canvas in Multiplayer

### ISSUE THREAD

**Issue by ZeburaBlack** [grondag/canvas#222]
![image](https://user-images.githubusercontent.com/56888661/111420766-31126a80-86c2-11eb-949d-97fa3116a898.png)

**Comment by grondag** [comment]
A ton of client side mods and you could not list a single one?

Please provide specifics sufficient to reproduce the defect.

**Comment by ZeburaBlack** [comment]
fabrication
loot beams
slimey floors
to name a few

**Comment by grondag** [comment]
Still no links, no versions, no specifics, no logs... to reproduce this could take anywhere from 30 minutes to the eventual heat death of the universe.

I don't have time to research ambiguous bug reports. Please try again.

**Comment by ZeburaBlack** [comment]
Fabric 0.11.3
API 0.32.0+1.16
Canvas 116-1.0.1267

Mods that are in question
[Fabrication](https://www.curseforge.com/minecraft/mc-mods/fabrication)
[Loot Beams](https://www.curseforge.com/minecraft/mc-mods/lootbeams)
[SlimyFloor](https://www.curseforge.com/minecraft/mc-mods/slimyfloor)

Log File from boot to entering multiplayer server.

[latest.log](https://github.com/grondag/canvas/files/6168823/latest.log)

Issues present
1-items in frames turn invisible
2-items dropped on ground from drops, natural, or from player turn invisible
3-Enchantment effect not visible outside inventory screen
4-particles not visible through water, or in water (such as magma/soulsand bubbles)

It also seems this happens with Sodium too, cannot pinpoint the exact cause but it seems after a certain point u have added so many mods, addition mods that add some kind of visual element, cause this to occur
remove any new omds, trimming mod list, or just removed Canvas solves the issue and more mods can be listed.

Modlist is currently 137 files in folder
253 in title screen.

Mod list (taken shortly after initial post)

![image](https://user-images.githubusercontent.com/56888661/111736682-b4fc5c00-8854-11eb-9c89-77cdb48385c9.png)

Link to download of modpack. (modpack currently only has issues 2 through 4, issue 1 arises when more mods like Slimy Floors or Lootbeams are added, and is only present in multiplayer)

ClientSide
https://www.dropbox.com/s/1jdbfqfoz3hyknf/EnchantmentCraftR11_2.zip?dl=0

ServerFiles
https://www.dropbox.com/s/r4l28zf4d1fr0p1/ServerFiles.zip?dl=0

And apologies from before, i'm an idiot sometimes. Sorry for the hassle.

**Comment by spiralhalo** [comment]
Canvas development has stopped for 1.16. I assume this modpack is unlikely to be available for 1.17 (at least with the same mods).

I would say feel free to reopen when the mods are on 1.17, although we would appreciate it if you can isolate the issues to minimal mods configuration and consider opening new issues for each issue separately. At the moment we don't have the resources to fix issues with entire modpacks or with older version of Canvas.
