### ISSUE TITLE
Game Fails to Start when using Canvas Renderer

### ISSUE THREAD

**Issue by toErIpNid** [grondag/canvas#226]
Tldr: testing a modpack and as soon as I put Canvas in it no longer works. It completely fails to start. 

Fabric Version 0.11.3.

Modlist: 
![Capture](https://user-images.githubusercontent.com/78389307/112072082-1109fd80-8b3f-11eb-956f-f9d6344d0f0f.PNG)

Crash Report: 
[crash-2021-03-22_18.46.19-client.txt](https://github.com/grondag/canvas/files/6185928/crash-2021-03-22_18.46.19-client.txt)

**Comment by toErIpNid** [comment]
Also, it's not cause of lithium. I tested it before without lithium and it still fails.

**Comment by CasuallyMatt** [comment]
issue seems to be transliterationlib, can you try removing it and checking if it runs

**Comment by CasuallyMatt** [comment]
which is probably included in some mod that i have no knowledge off. sike

**Comment by toErIpNid** [comment]
Does not run. Here's the latest crash report. 
[crash-2021-03-22_19.50.00-client.txt](https://github.com/grondag/canvas/files/6186108/crash-2021-03-22_19.50.00-client.txt)

**Comment by spiralhalo** [comment]
It might be a mixin conflict. Just noting that the two crash reports seem to report different crashes related to different mods.

Please try to isolate the crash with specific mod(s). And as development on 1.16 has stopped, feel free to reopen the issue if you're able to reproduce it on 1.17.
