### ISSUE TITLE
Questions about 1.17 shader based rendering.

### ISSUE THREAD

**Issue by K0-RR** [grondag/canvas#228]
To be honest I don't even know what this means but afaik canvas works in the same way so I wanted to ask what mc 1.17 means for canvas. Will it be easier to develop because of vanilla supporting some things or rather this changes so much that a rewrite would be needed to make this mod work in 1.17? How this change will affect performance? Discord would probably be a better place to ask these questions but I'm sure someone else would do it here sometime.

**Comment by grondag** [comment]
Cross posting from Curseforge

> Mojang recently announced they have finished the job they started a while back and moved all rendering to OpenGL Core Profile. https://www.minecraft.net/en-us/article/minecraft-snapshot-21w10a.
>
> This is wonderful news because it means we can use modern features on all platforms and are no longer fighting the game to introduce shaders - the vanilla game uses shaders.
>
> This will cause some backtracking and rework for Canvas (and other rendering mods) but is consistent with what I expected Mojang to do and in the end will allow a net simplification and easier development overall. Yay!
>
> However, it also means 1.16 rendering is essentially a dead end now, and so my efforts will be focused on the 1.17 snapshot going forward. This is a hobby project for me, and I am only one person, so I can't afford to maintain older versions if they are very different.
>
> 1.17 builds should become available "soon..."
