### ISSUE TITLE
Firstpersonrender mod does not work

### ISSUE THREAD

**Issue by AlexTheDolphin0** [grondag/canvas#231]
The firstperson render mod and notenoughanimations both do not work. the player shows up as invisible when uing firstpersonrender and notenoughanimations just does work

**Comment by spiralhalo** [comment]
Did you mean First-person Model mod? Looks like it hasn't been updated to 1.16.

Development on 1.16 has stopped so it has to wait until First-person Model is updated to 1.17. Feel free to reopen when it's updated.
