### ISSUE TITLE
Game doesn't fill window

### ISSUE THREAD

**Issue by Hyperbean18** [grondag/canvas#233]
![Screen Shot 2021-04-14 at 9 51 12 PM](https://user-images.githubusercontent.com/79054980/114753584-3e7c4c80-9d75-11eb-9296-86d0e404fad6.png)

I switched to sodium+indium+sodium extras for a bit, and when I tried to switch back to canvas, this is what my screen looks like. I tried changing the resolution in the launcher, but it didn't work. Using the latest version of canvas, and not in full screen

**Comment by Hyperbean18** [comment]
I'm still having this issue, still no idea what is causing it

my log, if it helps: [here](https://paste.gg/p/anonymous/fa2db53709d842e0b07778da8f7c2cc3)

**Comment by liquidoven** [comment]
Hi there did you end up figuring this out? I'm having the same issue

**Comment by Hyperbean18** [comment]
Yep! I just had to enter and exit full screen mode and it got fixed
