### ISSUE TITLE
Changing resource packs in 1.17 is causing texture mismatch

### ISSUE THREAD

**Issue by spiralhalo** [grondag/canvas#235]
Switching resource pack in/out causes certain quads to be rendered with the wrong material (not just the texture, as can be seen in this reflective blackstone brick side on a crafting table.)

![image](https://user-images.githubusercontent.com/8444172/115184500-2d7e6300-a108-11eb-8c2b-9aa2af54e4b4.png)

**Affected MC version(s):** 21w14a
**Affected Canvas version(s):** 1.0.1539
**Mods present during bug reproduction:** Trees Do Not Float, Fabric API

**Steps to reproduce:**
1. observe the sides of a crafting table, kelp, sand, texture of a bow item, an apple, poppy flower, etc (any of these)
2. load a resource pack with a lot of texture/material (the ones I used was a texture pack called "Bloom" and Lumi PBR Ext)
3. observe changes

**Workaround:** Restarting the game after changing resource packs prevents the bug (needs verification)

**Comment by spiralhalo** [comment]
Still happening as of commit 74ffaf8d6e287e03185eaf214d57606422b9a014 which I thought was the fix but I guess not.

![image](https://user-images.githubusercontent.com/8444172/123556196-04d3b300-d7b4-11eb-9237-42b6aa472361.png)

**Comment by spiralhalo** [comment]
Would like to add that it appears only the textures are mismatched now instead of the materials as you can see in this screenshot comparing mismatched textured blocks with their correct counterpart (notice the glossiness of the correct block)

![image](https://user-images.githubusercontent.com/8444172/123556337-ede19080-d7b4-11eb-8fd7-0ea958400574.png)

![image](https://user-images.githubusercontent.com/8444172/123556342-f89c2580-d7b4-11eb-8eae-bdfeb48442e9.png)

**Comment by ryleu** [comment]
I can also see this with peony bottom flowers with canvas/default

**Comment by spiralhalo** [comment]
More info:
- Loading a texture pack with **different resolution than the current atlas** causes the entire world to go crazy;

![image](https://user-images.githubusercontent.com/8444172/124373759-43d79c00-dcbf-11eb-9e3e-438fcb5cdc64.png)

- Loading a texture pack with **custom models** but same resolution causes minimal texture error;
- Loading a shader pack with **custom materials** also causes minimal texture error;
- Loading **Programmer Art** causes no texture error so far;
- Unlike the original issue, material properties and shader seems no longer affected now (correctly assigned by block id), only texture.

**Comment by spiralhalo** [comment]
Even more info:
- Only affects atlas textures. Entities seem unaffected.

Last tested Canvas 1.0.1689
