### ISSUE TITLE
Game crashed after loading a world

### ISSUE THREAD

**Issue by Mr-Waterscout** [grondag/canvas#236]
[crash-2021-04-19_14.25.21-client.txt](https://github.com/grondag/canvas/files/6339195/crash-2021-04-19_14.25.21-client.txt)
I made a new world and the game still crashed. I tried using the previous version of Fabric API but the game still crashed.

**Comment by TAKfsg** [comment]
Same issue here

**Comment by spiralhalo** [comment]
Looks related to https://github.com/FabricMC/fabric/commit/6d5e24549f1c6faa51b432ca03a507d6b30719ab

Please use fabric api 0.32.5+1.16 or older for the time being.

**Comment by Mr-Waterscout** [comment]
So use fabric api 0.31.0?

**Comment by Mr-Waterscout** [comment]
That worked, thanks!
