### ISSUE TITLE
Mining blocks looks weird in 21w15a

### ISSUE THREAD

**Issue by Mr-Waterscout** [grondag/canvas#237]
Canvas renderer version used: 1.0.1539
Issue: Block breaking graphic looks abnormal and mobs are not tinted red when hit
![2021-04-19_21 38 47](https://user-images.githubusercontent.com/73510808/115338470-bcff3280-a157-11eb-9bd4-0b23f2bd46ce.png)

**Comment by Reeses-Puffs** [comment]
*block breaking rotation go brrrrrrrrrr*

**Comment by Reeses-Puffs** [comment]
happens in 16a as well

**Comment by spiralhalo** [comment]
Fixed in https://github.com/grondag/canvas/commit/560784972a75ff497942923ce00b7112a801b7a8

**Comment by spiralhalo** [comment]
Mobs not tinted red is fixed in #269
