### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HCHSIAOawa** [grondag/canvas#240]
He appeared 
Could not find required mod: canvas requires {fabric-renderer-api-v1 @ [*]}
Creating Empty clause ?
I only have the Canvas Renderer mod installed

**Comment by Reeses-Puffs** [comment]
The error says everything, you are missing a dependency. Go install it.

**Comment by HCHSIAOawa** [comment]
> The error says everything, you are missing a dependency. Go install it.
what is that dependency

**Comment by Reeses-Puffs** [comment]
Read the error, it says what it is

**Comment by HCHSIAOawa** [comment]
> Read the error, it says what it is

Thanks^^

**Comment by tux7k** [comment]
> 
> 
> The error says everything, you are missing a dependency. Go install it.

The new Fabric API introduced a new renderer that kinda broke everything

**Comment by tux7k** [comment]
Try downgrading fabric api too, it will work

**Comment by spiralhalo** [comment]
I suppose this is resolved.

Make sure to use latest Canvas and Fabric API folks. As of writing latest Canvas builds in 1.16 and 1.17 require Fabric API version 0.32.9 or higher.
