### ISSUE TITLE
Canvas crashes modpack.

### ISSUE THREAD

**Issue by toErIpNid** [grondag/canvas#245]
[crash-2021-05-04_19.39.05-client.txt](https://github.com/grondag/canvas/files/6424569/crash-2021-05-04_19.39.05-client.txt)
 All versions are latest except for minecraft, which is 1.16.5

**Comment by heymanMC** [comment]
downgrade your fabric api version to 0.32.5

**Comment by toErIpNid** [comment]
Made a new modpack, tried canvas before and after downgrading the api with no success. 

Latest crash log: 
[crash-2021-05-07_20.07.52-client.txt](https://github.com/grondag/canvas/files/6444901/crash-2021-05-07_20.07.52-client.txt)

**Comment by IMS212** [comment]
API is not downgraded to **0.32.5** in that log?

**Comment by grondag** [comment]
Duplicate of #234
