### ISSUE TITLE
Crash when leaving world

### ISSUE THREAD

**Issue by sharpenedblade** [grondag/canvas#248]
When leaving world with `save and quit` the game crashes with `Error: java.lang.NullPointerException: Cannot read field "field_1724" because "client" is null`. Tihs does not happen all the time

**Comment by spiralhalo** [comment]
That isn't very descriptive. We need the full stack trace and mod list, basically the full crash report.

**Comment by sharpenedblade** [comment]
Sneakhold Mod was the cause, closing issue.
