### ISSUE TITLE
crashes when opening world

### ISSUE THREAD

**Issue by Hyperbean18** [grondag/canvas#254]
The game loads the world and shows it for a split second before it suddenly exits and shows the saving world screen

[crash report here](https://gist.githubusercontent.com/natanfudge/ed625e69c84ec5d4109f733a7b6f182c/raw/f658fe39f828c1d22c57072584a7aee8b5ece8ec/crash.txt)

**Comment by Shadowevil015** [comment]
Hi, Canvas is currently incompatible with Fabric API above v0.32.5, so you'll need to downgrade [to this one](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3248105)

**Comment by sharpenedblade** [comment]
Or you can use spiralhalo's 1.16 lts fork of canvas of fapi 0.32.8+

**Comment by Hyperbean18** [comment]
yep, it works now! Thanks
