### ISSUE TITLE
Crash on loading in the world

### ISSUE THREAD

**Issue by JoJazzy** [grondag/canvas#258]
Whenever I go into any world my game crashes, the worldgen goes through and all, I even managed to log in for a sec but then promptly crashed with the client returning: 

java.lang.NoSuchMethodError: net.fabricmc.fabric.impl.client.rendering.WorldRenderContextImpl.prepareBlockOutline(Lnet/minecraft/class_4588;Lnet/minecraft/class_1297;DDDLnet/minecraft/class_2338;Lnet/minecraft/class_2680;)V

The only mods I'm using are Jumploader, the Fabric API and Canvas

Here's the full crash report and log, I hope these can be of any help:
[crash-2021-05-23_22.01.18-client.txt](https://github.com/grondag/canvas/files/6528850/crash-2021-05-23_22.01.18-client.txt)
[latest.log](https://github.com/grondag/canvas/files/6528851/latest.log)

**Comment by spiralhalo** [comment]
Duplicate of #234

Solution: use latest github release: https://github.com/grondag/canvas/releases/tag/mc116-one-1.0.1511-unstable
(Will be published in CurseForge soon)

**Comment by JoJazzy** [comment]
Thanks a lot!
