### ISSUE TITLE
Canvas renderer causes crashes with java 17.

### ISSUE THREAD

**Issue by Kichura** [grondag/canvas#259]
When attempting to run canvas renderer using java 17, the game just crashes with a repeated log flood of errors. This issue does **NOT** apply to related rendering mods such as Sodium.

![image](https://user-images.githubusercontent.com/68134602/119730073-9c707980-be75-11eb-98c8-abdc5b2bc531.png)

Workaround: Using java 16 or older will allow canvas renderer to run just fine without issues.

**Comment by ghost** [comment]
Minecraft doesn't support java 17

**Comment by Kichura** [comment]
> 
> 
> Minecraft doesn't support java 17

Then how come it CAN run just fine with other mods including vanilla itself? - I used a pre-release of [AdoptOpenJDK 17](https://github.com/AdoptOpenJDK/openjdk17-binaries/releases) from github itself in case it really isn't believable.
![image](https://user-images.githubusercontent.com/68134602/119847688-7c8b9500-bf0b-11eb-889e-d0d5cbf82e2d.png)

**Comment by Reeses-Puffs** [comment]
"not supported" doesn't mean "can't run on"

**Comment by ghost** [comment]
idk the changelog says it explicitly supports 16 i didnt know 17 works

**Comment by Kichura** [comment]
> 
> 
> idk the changelog says it explicitly supports 16 i didnt know 17 works

17 has existed for quite some time now although it's currently in pre-release stage since it will (hopefully) be released in september this year or next.

Although there wasn't any public documentation given out by adoptopenjdk as far as i knew, only their github showed that it was a thing in first place.

**Comment by grondag** [comment]
The latest Canvas build (1578) is running for me on the [latest JDK 17 build](https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/tag/jdk-2021-05-07-13-31).
