### ISSUE TITLE
Light levels don't change

### ISSUE THREAD

**Issue by Mr-Waterscout** [grondag/canvas#263]
I was caving and noticed that the light levels did not change, the game kept rendering everything in light level 15, I'm pretty sure.

**Comment by Mr-Waterscout** [comment]
Using canvas 1.17-1.0.1578

**Comment by grondag** [comment]
Which pipeline do you have active?  With dev the lighting is crazy wrong, which is why it is still dev...

**Comment by Mr-Waterscout** [comment]
I think it was dev, I'll try with the other pipelines later

**Comment by Mr-Waterscout** [comment]
![2021-06-01_12 33 43](https://user-images.githubusercontent.com/73510808/120380234-c68ec500-c2d5-11eb-84d1-9c3b1e994366.png)
With the basic pipeline

**Comment by Mr-Waterscout** [comment]
It should be almost pitch black

**Comment by grondag** [comment]
Interesting.  Two more questions:  1) Any other mods present and 2) does it happen in any enclosed space (include new digs) or only in some areas?  If it's specific to area, what's the Y-level and biome here?

**Comment by Mr-Waterscout** [comment]
The only mod I was using was canvas, and it does happen with enclosed areas. I don't think it's specific to the area.

**Comment by spiralhalo** [comment]
When changing pipelines, especially from/to Dev or third-party, make sure to recompile (default Hotkey '=') or you might not see proper light levels. This is fixed in #262.

**Comment by Mr-Waterscout** [comment]
It's not canvas, it's my vanilla game. I don't know why it's not displaying light levels below 15.

**Comment by Mr-Waterscout** [comment]
I fixed the issue, I had to update the brightness setting.
