### ISSUE TITLE
Add an issue template

### ISSUE THREAD

**Issue by Reeses-Puffs** [grondag/canvas#267]

**Comment by Reeses-Puffs** [comment]
tfw you press enter by mistake and it adds the issue

**Comment by Reeses-Puffs** [comment]
Affected Canvas versions:

Description of the issue:

Link to paste site with logs:

**Comment by ArkQuark** [comment]
Optional(options.txt with canvas.json5 and canvas_pipeline_options.json5) if it needed

**Comment by cmdremily** [comment]
Here's a fairly standard template that can be used:

## System data
Minecraft Version: <FILL ME IN>
Canvas Version: <FILL ME IN>
Operating System: <FILL ME IN>
Graphics Card: <FILL ME IN>

## Other mods and versions installed 
* fabric-1.2.3
* lumi-4.5.6

## How you triggered the behavior
1. start minecraft
2. log into singleplayer world
3. run into creeper

## What you expected would happen
Unicorn farts and confetti would appear.

## What actually happened
I exploded.

## Logs
....

**Comment by grondag** [comment]
Thanks!
