### ISSUE TITLE
Game crashed at map load - modded environment

### ISSUE THREAD

**Issue by MetromapSVG** [grondag/canvas#276]
Tried out canvas and this happened, with multiple mods as a test.

Runtime environment: Apple M1, 8GB RAM

Hopefully this helps.

[hs_err_pid4022.log](https://github.com/grondag/canvas/files/6644621/hs_err_pid4022.log)

**Comment by grondag** [comment]
Thank you for the report.  I develop on a Mac and am excited about the Apple silicon Macs.  Unfortunately, I don't have one yet and I suspect there are still some driver issues beyond my control that would make it difficult to resolve this now.  

I am going to close this issue but I hope to revisit M1 compatibility when circumstances allow.
