### ISSUE TITLE
.jar File for 1.17 won't open.

### ISSUE THREAD

**Issue by tnguyen2601** [grondag/canvas#277]
Downloaded the "canvas-mc117-1.17-1.0.1638.jar" file and clicked on it. Nothing happend.

**Comment by CasuallyMatt** [comment]
It would be worrying if something had happened

**Comment by Pyrofab** [comment]
Unlike Optifine, Canvas needs a modloader (specifically the Fabric modloader) to work. You can find information on how to install a Fabric mod on the relevant wiki: https://fabricmc.net/wiki

**Comment by Reeses-Puffs** [comment]
~~tfw you expect everything to work like optifine~~
