### ISSUE TITLE
Textures are mismatched after loading a resource pack

### ISSUE THREAD

**Issue by alistairporter** [grondag/canvas#280]
Upon loading a resource pack, the textures appear to be mismatched with blocks, items and particles being affected, the issue persists after switching back to vanilla textures.
The issue seems to resolve itself if the game is restarted and cannot be triggered by reloading textures with F3+T, It can be reproduced with a fresh instance of minecraft, with the fabric loader, fabric api, and canvas added to it and affects any resource pack (I used the Faithful resource pack for testing, but it also affects vanilla tweaks).

### Screenshots

![2021-06-21_21 21 11](https://user-images.githubusercontent.com/17324936/122825408-cd5b9700-d2d9-11eb-93a0-7f36e0f2819b.png)

![2021-06-21_21 20 51](https://user-images.githubusercontent.com/17324936/122825427-d3ea0e80-d2d9-11eb-8037-bf12bee230a1.png)

![2021-06-21_21 09 46](https://user-images.githubusercontent.com/17324936/122825453-dc424980-d2d9-11eb-90a0-724d9830faf3.png)

![2021-06-21_21 11 44](https://user-images.githubusercontent.com/17324936/122825464-e19f9400-d2d9-11eb-98bb-4a03f6e1069b.png)

![2021-06-21_21 09 20](https://user-images.githubusercontent.com/17324936/122825536-fc720880-d2d9-11eb-8426-30b32ff41f2d.png)

### System data

Minecraft Version: 1.17
Launcher: MultiMC 5
Canvas Version: 1.0.1641
Operating System: Ubuntu 21.04
Graphics Card: NVIDIA GeForce GTX 1060 6GB
Other mods and versions installed:
- fabric-0.11.6
- fabric-api-0.36.0+1.17
### Logs

[https://pastebin.com/ytaXhyu7](https://pastebin.com/ytaXhyu7)

**Comment by Reeses-Puffs** [comment]
Duplicate of #235

**Comment by alistairporter** [comment]
Ah, didnt see that one
