### ISSUE TITLE
Changing resource pack in game causes issues

### ISSUE THREAD

**Issue by heymanMC** [grondag/canvas#287]
**System Informatinon**

- Minecraft Version: 1.17
- Canvas Version: mc117-1.17-1.0.1677-unstable
- Operating System: Windows 10
- Graphics Card: NVIDIA RTX 3080

**Other mods and versions installed**

- Fabric API 0.34.9+1.17
- Mod Menu 2.0.0-beta.7

**How you triggered the behavior**

- Launch minecraft.
- Open singleplayer world.
- Change resourcepack (specifically, one that modifies textures; not a pack like Lumi Lights) to something else.

**What you expected would happen**

- The new resourcepack should apply normally.

**What actually happened**

- Textures seem to be all messed up and moved around, see screenshots.

**Screenshots**

*Before applying new resourcepack in game:*
![2021-06-29_16 13 10](https://user-images.githubusercontent.com/38384673/123874148-e9bc8c80-d8f4-11eb-9473-1dba9cce2953.png)

*After:*
![2021-06-29_16 12 27](https://user-images.githubusercontent.com/38384673/123874170-f2ad5e00-d8f4-11eb-94bb-7c00b4a0cee1.png)

*Resourcepack added in vanilla (to prove it isn't the resourcepack at fault):*
![2021-06-29_16 18 08](https://user-images.githubusercontent.com/38384673/123874589-a4e52580-d8f5-11eb-81db-1007230d01a9.png)

**Logs**
See here for the log. Note: nothing out of the ordinary found in the logs.
[log.txt](https://github.com/grondag/canvas/files/6736819/log.txt)

**Comment by netkv** [comment]
can confirm, same thing happens to me on 1.17 on linux with amd vega 8 igpu

**Comment by heymanMC** [comment]
Duplicate of https://github.com/grondag/canvas/issues/235
