### ISSUE TITLE
Chunks don't load after coming out of a particular nether portal

### ISSUE THREAD

**Issue by spiralhalo** [grondag/canvas#290]
**System Information**

- Minecraft Version: 1.17
- Canvas Version (non exhaustive list): 
  - canvas-mc117-1.17-1.0.1690
  - canvas-mc117-1.17-1.0.1689
- Operating System: Windows 10
- Graphics Card: GeForce RTX 2060 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 457.51, NVIDIA Corporation

**Other mods and versions installed**

audiooutput-0.0.4
blast-1.6.2
fabric-api-0.34.8+1.17
modmenu-2.0.0-beta.5
PresenceFootsteps-r31-1.17-rc1
respackopts-2.1.0
https://github.com/spiralhalo/LumiLights/commit/dec073485212c7c8d839b42e016b38fe9bfb4f97
https://github.com/spiralhalo/LumiPBRExt/commit/83f835ce214adb9f888e6926907cf523f9cd7c06
https://github.com/spiralhalo/LumiPBRCompat/commit/1b4f909598c6d8292664b3ac0e94f56e31ff912c

**How you triggered the behavior**

- Load the attached world (8 MB): [2021-07-04_11-09-39_CanvasPortalBug.zip](https://github.com/grondag/canvas/files/6759361/2021-07-04_11-09-39_CanvasPortalBug.zip)
- `/tp 140 64 260`
- (If it stops rendering I guess this spot is cursed -> reload world)
- Enter nether portal
- (If it stops rendering -> reload world)
- Walk out and enter nether portal again
- Arrive in the overworld

**What you expected would happen**

- The chunks load

**What actually happened**

- The chunks don't load until walking out of the nether portal for a ~5 blocks

**Logs and screenshots**

Log: https://gist.github.com/spiralhalo/d8db1f112f17ea243ecfbca3d47d2ecb

Video:
- note: Distortion is turned off
- I demonstrated walking out for brevity, but the chunks will never load if I don't walk out of the portal for 5 blocks forward

https://user-images.githubusercontent.com/8444172/124373076-a0d05380-dcb9-11eb-8902-bf7cd1a58d03.mp4

**Comment by grondag** [comment]
I've seen this, too.  No idea why it's happening.

**Comment by spiralhalo** [comment]
What interesting for me is that apparently `/tp` also causes the issue but reloading the world while in that exact spot doesn't, so some cached state in the iterator/occluder is causing it.

And unlike the previous NPE/ArrayIndexOOB this one doesn't require full restart, just need to walk around a little from the glitchy spot. (I call it "glitchy spot" because it doesn't affect all tp/nether portal).

**Comment by spiralhalo** [comment]
Seems to be improving in recent release(s). Previously they won't load at all until moving to a different spot. Now the nearest chunk loads, and the rest loads after turning the camera for some amount.

**Comment by supsm** [comment]
looks like this was fixed along with other teleportation-related rendering issues. can't reproduce in latest canvas
