### ISSUE TITLE
(suggestion) option to remove custom enchantment glint

### ISSUE THREAD

**Issue by shiftlessturtle** [grondag/canvas#296]
I don't like the custom enchantment glint and I don't think there's a way to get rid of it, I prefer the vanilla tweaks enchantment glint

**Comment by spiralhalo** [comment]
This is already fixed in https://github.com/grondag/canvas/commit/0dab2b2fa322069646fb36a61cc964aa707e8400 and will be released soon.

**Comment by supsm** [comment]
close this issue now. I know you can do it awoo

**Comment by spiralhalo** [comment]
I would let people see the issue until it’s released to avoid duplicates or leave it to the issue author.

**Comment by spiralhalo** [comment]
It's released https://github.com/grondag/canvas/releases/tag/mc117-1.17-1.0.1739-unstable

Feel free to give feedback or close the issue.

**Comment by spiralhalo** [comment]
Latest curseforge release don't contain the custom enchantment glint anymore so I suppose this is no longer relevant.
