### ISSUE TITLE
Pillaring upwards with any block results in game crash.

### ISSUE THREAD

**Issue by calebhartt** [grondag/canvas#304]
**System Information**

- Minecraft Version: 1.17
- Canvas Version: 1.0.1793
- Operating System: Windows 10 Home
- Graphics Card: RTX 2060

**Other mods and versions installed**

- fabric API

**How you triggered the behavior**

- start minecraft
- log into singleplayer world
- pillar upwards with any block (spamming right click and holding down right click yield the same result)

**What you expected would happen**

- Nothing

**What actually happened**

- Minecraft crashed

**Logs and screenshots**

Crash report:
[crash-2021-07-14_14.00.59-client.txt](https://github.com/grondag/canvas/files/6818407/crash-2021-07-14_14.00.59-client.txt)

I've tested it multiple times on my pc and have gotten the same result. All canvas settings were on "Yes," with the exclusion of the technical stabilization settings (of which I can't remember the name) which were unnecessary for my PC specs. Canvas and Fabric API were the only mods installed.

**Comment by spiralhalo** [comment]
No longer reproducible in latest.
