### ISSUE TITLE
Canvas ignores castShadows(false) in FREX MaterialFinder

### ISSUE THREAD

**Issue by Kneelawk** [grondag/canvas#308]
**System Informatinon**

- Minecraft Version: 1.17.1
- Canvas Version: 1.0.1816
- Operating System: Linux Kubuntu 20.04.2 LTS
- Graphics Card: GeForce GTX 1060 6GB/PCIe/SSE2

**Other mods and versions installed**

- architectury-2.0.16 (runtime only)
- bitraster-1.0.7 (runtime only)
- fabric-0.36.1+1.17
- frex-5.3.226
- heart-of-the-machine-0.2.0-SNAPSHOT (My mod and the way I encountered this bug.)
- jmx-1.22.201
- libblockattributes-0.9.1-pre.1
- libmultipart-0.6.3
- libnetworkstack-0.5.2
- lumilights-0.25 (resource pack)
- lumiPBRExt-0.21 (resource pack)
- modmenu-2.0.2 (runtime only)
- rei-6.0.260 (runtime only)
- simple-pipes-0.6.1 (runtime only)
- terraformersmc-shapes-1.0.4
- exotic-blocks-1.6.192 (runtime only)

**How you triggered the behavior**

- Use a FREX `RenderMaterial` that has been constructed with the `castShadows(false)` parameter in a block entity renderer.
- Use `FrexVertexConsumerProvider` to obtain a `VertexConsumer` using this `RenderMaterial`.
- Render something with the obtained `VertexConsumer`.

**What you expected would happen**

- Anything rendered with the obtained `VertexConsumer` would not cast a shadow, even in LumiLights or Canvas-Dev renderers.

**What actually happened**

- Objects rendered with the obtained `VertexConsumer` do cast shadows, despite the `castShadow(false)` parameter being specified in their `RenderMaterial`.

**Logs and screenshots**

- [latest.log](https://github.com/grondag/canvas/files/6852287/latest.log)
- [debug.log](https://github.com/grondag/canvas/files/6852303/debug.log)
- ![2021-07-20_19 00 10](https://user-images.githubusercontent.com/2180089/126420090-feaa3bc9-da4a-4cf2-bfd1-55a5621db6a0.png)

**Repository Links**

- `RenderMaterial` creation: [HotMRenderMaterials.kt](https://github.com/Heart-of-the-Machine/heart-of-the-machine/blob/458e8b6bbb19efc6bf62a6d2b52961e6a1cf8dad/src/main/kotlin/com/github/hotm/client/render/HotMRenderMaterials.kt#L30)
- `VertexConsumer` use: [AuraNodeRendererUtils.kt](https://github.com/Heart-of-the-Machine/heart-of-the-machine/blob/458e8b6bbb19efc6bf62a6d2b52961e6a1cf8dad/src/main/kotlin/com/github/hotm/client/render/blockentity/AuraNodeRendererUtils.kt#L48)
- Repository link: [Heart-of-the-Machine/heart-of-the-machine](https://github.com/Heart-of-the-Machine/heart-of-the-machine/tree/458e8b6bbb19efc6bf62a6d2b52961e6a1cf8dad)

**Notes**

This issue is demonstrated in LumiLights for shadow clarity, but happens in Canvas-Dev as well.

**Comment by spiralhalo** [comment]
Thanks for your report! This should be fixed in 2af5ea652be14cb9371cd6b99c9808e909b910fa or d4477db64571cc8d327e7b5e59427f4d3296ce51. Reply if found otherwise.
