### ISSUE TITLE
Can't launch the game

### ISSUE THREAD

**Issue by Enessounnet** [grondag/canvas#309]
I just can't launch the game, it keeps crashing

Here's the crash report :

----------------------------------------------------------------

MultiMC version: 0.6.12-1530

Minecraft folder is:
E:/Jeux/MultiMC/instances/1.17/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_301/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_301, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  E:/Jeux/MultiMC/instances/1.17/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  E:/Jeux/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  E:/Jeux/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  E:/Jeux/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  E:/Jeux/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  E:/Jeux/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  E:/Jeux/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  E:/Jeux/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  E:/Jeux/MultiMC/libraries/com/mojang/blocklist/1.0.5/blocklist-1.0.5.jar
  E:/Jeux/MultiMC/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  E:/Jeux/MultiMC/libraries/com/github/oshi/oshi-core/5.7.4/oshi-core-5.7.4.jar
  E:/Jeux/MultiMC/libraries/net/java/dev/jna/jna/5.8.0/jna-5.8.0.jar
  E:/Jeux/MultiMC/libraries/net/java/dev/jna/jna-platform/5.8.0/jna-platform-5.8.0.jar
  E:/Jeux/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  E:/Jeux/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.14.1/log4j-slf4j18-impl-2.14.1.jar
  E:/Jeux/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  E:/Jeux/MultiMC/libraries/com/mojang/javabridge/1.1.23/javabridge-1.1.23.jar
  E:/Jeux/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  E:/Jeux/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  E:/Jeux/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  E:/Jeux/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  E:/Jeux/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  E:/Jeux/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  E:/Jeux/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  E:/Jeux/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  E:/Jeux/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  E:/Jeux/MultiMC/libraries/com/mojang/authlib/2.3.31/authlib-2.3.31.jar
  E:/Jeux/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  E:/Jeux/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  E:/Jeux/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  E:/Jeux/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  E:/Jeux/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  E:/Jeux/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar
  E:/Jeux/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar
  E:/Jeux/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  E:/Jeux/MultiMC/libraries/net/fabricmc/intermediary/1.17/intermediary-1.17.jar
  E:/Jeux/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  E:/Jeux/MultiMC/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar
  E:/Jeux/MultiMC/libraries/net/fabricmc/tiny-remapper/0.4.2/tiny-remapper-0.4.2.jar
  E:/Jeux/MultiMC/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar
  E:/Jeux/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  E:/Jeux/MultiMC/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
  E:/Jeux/MultiMC/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  E:/Jeux/MultiMC/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  E:/Jeux/MultiMC/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  E:/Jeux/MultiMC/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  E:/Jeux/MultiMC/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  E:/Jeux/MultiMC/libraries/net/fabricmc/fabric-loader/0.11.6/fabric-loader-0.11.6.jar
  E:/Jeux/MultiMC/libraries/com/mojang/minecraft/1.17/minecraft-1.17-client.jar

Native libraries:
  E:/Jeux/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  E:/Jeux/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  E:/Jeux/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  E:/Jeux/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  E:/Jeux/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  E:/Jeux/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  E:/Jeux/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  E:/Jeux/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] canvas-mc117-1.17-1.0.1802
  [✔️] cloth-config-5.0.34-fabric
  [✔️] fabric-api-0.36.0+1.17
  [✔️] frex-mc117-5.3.226
  [✔️] illuminations-1.6.1
  [✔️] modmenu-2.0.3

Params:
  --username  --version MultiMC5 --gameDir E:/Jeux/MultiMC/instances/1.17/.minecraft --assetsDir E:/Jeux/MultiMC/assets --assetIndex 1.17 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx3072m, -Duser.language=en]

ID du processus Minecraft : 19144

Using onesix launcher.

[14:55:46] [main/INFO]: Loading for game Minecraft 1.17
[14:55:46] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: canvas requires {java @ [>=16]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-loader-0.11.6.jar:?]
	... 13 more
Le processus s'est arrêté avec le code de sortie 1.
Clipboard copy at: 21 Jul 2021 14:55:53 +0200
Clipboard copy at: 21 Jul 2021 14:55:54 +0200

**Comment by grondag** [comment]
You need Java 16 to run Canvas for 1.17.  I recommend the OpenJDK distribution.
