### ISSUE TITLE
where did the dynamic lights go???

### ISSUE THREAD

**Issue by NattoRiisa** [grondag/canvas#332]
**System Information**

- Minecraft Version: 1.17.1
- Canvas Version: 1.0.2004 (and 1.0.2035)
- Operating System: Windows 10 Home
- Graphics Card: INTEL HD GRAPHICS 520

**Other mods and versions installed**
(MAIN ONE)
  [✔️] AdditionalAdditions-2.1.3
  [✔️] advanced-xray-fabric-1.17-0.6.0-build.8
  [✔️] architectury-2.2.21-fabric
  [✔️] autoconfig1u-3.3.1
  [✔️] betterbiomeblend-1.17.0-1.2.3-fabric
  [✔️] capes-1.2.0
  [✔️] cloth-config-5.0.34-fabric
  [✔️] DungeonsArise-1.17.1-2.1.47-fabric-release
  [✔️] fabric-api-0.37.1+1.17
  [✔️] fabric-language-kotlin-1.6.3+kotlin.1.5.21
  [✔️] FatExperienceOrbs-1.0.1
  [✔️] high-level-enchants-v0.2.0
  [✔️] hydrogen-fabric-mc1.17.1-0.3
  [✔️] InfinityRooms-1.3-1.17.x
  [✔️] krypton-0.1.4
  [✔️] lambdynamiclights-2.0.1+1.17
  [✔️] levelz-1.0.8
  [✔️] modmenu-2.0.4
  [✔️] nether-ore-1.0.0
  [✔️] replaymod-1.17.1-2.6.1
  [✔️] repurposed_structures_fabric-2.3.3+1.17.1
  [✔️] resource-overhaul-2.11.7-FABRIC-MC1.17-1.17.1
  [✔️] RoughlyEnoughItems-6.0.279-alpha-fabric
  [✔️] starlight-1.0.0+fabric.73f6d37

(TESTING ONE)

  [✔️] canvas-mc117-1.17-1.0.2004
  [✔️] fabric-api-0.37.1+1.17
  [✔️] modmenu-2.0.4

**How you triggered the behavior**

- I start the world
- I log into any world/server
- go to anywhere dark (such as a block light of 3-6 or darker based on the mods)

**What you expected would happen**

- Dynamic Lights on the light affected blocks

**What actually happened**

- No dynamic lights occurred..

**Logs and screenshots**
- Please attach or link to complete log(s). Even if the log doesn't _seem_ to be relevant, it often may.
https://pastebin.com/ik9Q0F24 (MAIN LOG)
https://pastebin.com/hX0EiYcv (BACKUP LOG - OTHER LOGS)
- Screenshots are also very helpful for illustrating visual defects
- Canvas with the mods listed

MAIN ONE

![2021-09-19_11 23 43](https://user-images.githubusercontent.com/52566765/133914372-330363eb-1912-4e88-8010-20c2016987c1.png)

TESTING ONE
![2021-09-19_11 48 14](https://user-images.githubusercontent.com/52566765/133914806-c2c027ba-a619-41d2-a2a3-15b0ff212e61.png)

1.0.2035 ONE WITH F3
![2021-09-19_12 03 08](https://user-images.githubusercontent.com/52566765/133915035-daaee443-83ee-428d-8cde-d05aebcc661f.png)
I deeply apologize if this issue bothers you since I have no idea what's causing this.

**Comment by NattoRiisa** [comment]
turns out i forgot to enable the pack, my bad

**Comment by NattoRiisa** [comment]
nothing actually happened even with the default pack opened, at least for the main one

**Comment by Pikalyx** [comment]
Try taking out LambDynamicLights, having two dynamic light features doesn't sound right.

**Comment by supsm** [comment]
Can you still reproduce this?

**Comment by NattoRiisa** [comment]
> Can you still reproduce this?

sorry for the very late response i'll see if i can replicate this on 1.17.1 or the latest

**Comment by ambrosia13** [comment]
It;s better to test for 1.19.3 or later because older versions are not actively supported usually

**Comment by NattoRiisa** [comment]
i can't reproduce it now because i must have used a different cpu or something (i have since moved to a desktop so)
1.17.1 - unable to reproduce on the last 1.17.1 version (2230)
![2023-05-03_12 10 51](https://user-images.githubusercontent.com/52566765/235833159-6a4d87b3-6677-4c9c-aff5-1f72a6e7adbe.png)

1.19.3 - unable to reproduce on the latest modrinth build (2535)
1.19.4 - unable to reproduce on the latest github build (2571)
![2023-05-03_12 27 14]
(https://user-images.githubusercontent.com/52566765/235833141-4116d7be-3dae-4b5d-b2d2-6cab4b1398ee.png)

**Comment by NattoRiisa** [comment]
i guess it's a graphic related issue so

**Comment by supsm** [comment]
Are you able to still access and test with the old device? If not I will close the issue.

**Comment by NattoRiisa** [comment]
i cannot access the old device

so i guess it's closed as is
sorry for not reproducing it sooner ><
