### ISSUE TITLE
A few custom model parts don't light except with held items

### ISSUE THREAD

**Issue by Variadicism** [grondag/canvas#333]
Hello! I use quite a few resource pack assets that have custom models. Unfortunately, a couple of them seem to encounter an issue with Canvas that causes them to render parts of them as if they are in complete darkness.

However, one exception to this is that when I hold a light-emitting block or item such as glowstone or a torch, the light correctly lights these unlit model parts.

This is best exhibited by the "short grass" that sits atop the grass block models in [the Fancy resource pack](https://texture-packs.com/resourcepack/fancy/).

Here is what I see in this resource pack while running Canvas renderer:
![2021-10-05_21 43 00](https://user-images.githubusercontent.com/64975260/136331213-272399c5-2e7e-4453-8ef4-aae235c4a507.png)

Here is what happens when I hold glowstone:
![2021-10-05_21 43 09](https://user-images.githubusercontent.com/64975260/136331333-db508fd8-ae2d-43e5-80e0-fba5ac2faa31.png)

I love the short grass model from the Fancy resource pack; I would love a fix to this so that I could use it again with this renderer!

_P.S.: I only tried Canvas for the first time recently and I have never had a framerate like this! For me, it was not only so much higher than OptiFine, but also so much higher than Sodium... and Sodium breaks so many more resource pack features and has far fewer configuration options! I can't thank you enough for making this!_

**Comment by spiralhalo** [comment]
Happens also with blocky custom models (stalactite from Patrix's resourcepack).
Light smoothing level has no effect.

![image](https://user-images.githubusercontent.com/8444172/141206061-77b3e4c5-2e76-4cca-9405-b6bd481097db.png)

**Comment by grondag** [comment]
Should hopefully be improved as part of https://github.com/vram-guild/frex/issues/3
