### ISSUE TITLE
Custom pipeline configurations (defaults/types) not being updated correctly at all

### ISSUE THREAD

**Issue by ambrosia13** [grondag/canvas#334]
**System Informatinon**

- Minecraft Version: 1.17.1
- Canvas Version: Tested 2035 and 2082
- Operating System: Windows 10
- Graphics Card: RTX 3060

**Other mods and versions installed**
(taken from latest.log)
	- ambientenvironment@6.0.21
	- antighost@1.17.1-fabric0.36.1-1.1.4
	- appleskin@mc1.17-2.1.3
	- axolotlitemfix@1.1.2
	- betterbeds@1.2.0
	- betterbiomeblend@1.17.0-1.2.9-fabric
	- blur@2.1.0
	- canvas@1.0.2082
	- charmonium@3.3.0
	- cloth-basic-math@0.5.1
	- cloth-config2@5.0.38
	- com_electronwill_night-config_core@3.6.2
	- com_electronwill_night-config_toml@3.6.2
	- com_moandjiezana_toml_toml4j@0.7.2
	- com_velocitypowered_velocity-native@1.1.0-SNAPSHOT
	- compactstatuseffects@2.0.1
	- crowdin-translate@1.3+1.17
	- dark-loading-screen@1.6.10
	- easiervillagertrading@1.17.1-fabric0.36.1-1.5.4
	- entityculling@1.3.3
	- fabric@0.40.1+1.17
	- fabric-api-base@0.3.0+a02b44633d
	- fabric-api-lookup-api-v1@1.3.0+cbda931818
	- fabric-biome-api-v1@3.2.0+cbda931818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+cbda931818
	- fabric-content-registries-v0@0.3.0+cbda931818
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.2.3+87cc6e4c18
	- fabric-events-interaction-v0@0.4.10+fc40aa9d18
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+cbda931818
	- fabric-item-api-v1@1.2.4+cbda931818
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+cbda931818
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.4+kotlin.1.5.30
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.13+cbda931818
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+cbda931818
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+cbda931818
	- fabric-renderer-indigo@0.4.8+cbda931818
	- fabric-renderer-registries-v1@3.2.3+4658223018
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446318
	- fabric-rendering-fluids-v1@0.1.14+4658223018
	- fabric-rendering-v0@1.1.4+4658223018
	- fabric-rendering-v1@1.8.2+ffb6d41e18
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+cbda931818
	- fabric-screen-handler-api-v1@1.1.8+cbda931818
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.2.1+b06cb95b18
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.3.1+4658223018
	- fabricloader@0.11.6
	- fallingleaves@1.7.3+1.17.1
	- fermion@2.11.256
	- fermion-orientation@1.2.256
	- fermion-varia@2.6.256
	- ferritecore@3.0.3
	- fiber@0.23.0-2
	- fpsdisplay@1.4.1+1.17
	- frex@6.0.46
	- gbfabrictools@1.3.4+1.17
	- here-be-no-dragons@1.0.0
	- iknowwhatimdoing@3.1.0
	- io_vram_bitraster@1.5.50
	- io_vram_special-circumstances@1.9.5
	- itemmodelfix@1.0.2+1.17
	- jankson@3.0.1+j1.2.0
	- java@16
	- json-model-extensions@1.22.216
	- kirin@1.9.1
	- krypton@0.1.4
	- lazydfu@0.1.2
	- libzoomer@0.2.1+1.17
	- lithium@0.7.4
	- minecraft@1.17.1
	- musicdr@1.2.1
	- okzoomer@5.0.0-beta.2+1.17
	- org_anarres_jcpp@1.4.14
	- org_aperlambda_lambdajcommon@1.8.1
	- org_jetbrains_kotlin_kotlin-reflect@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.30
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.1
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.1
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.2
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.2
	- pling@1.4.0
	- presencefootsteps@r32-1.17-rc1
	- satin@1.6.0-nightly.1.17-pre3
	- screenshotclipboard@1.0.6
	- spruceui@3.2.0+1.17
	- starlight@1.0.0+fabric.73f6d37
	- wthit@3.9.1

**How you triggered the behavior**

- Create pipeline configuration
- In these particular instances, I set several options as booleans with default "true". 
- In one scenario, I changed two options to default "false", but after several restarts and resource reloads, the default that the game tells me is "true".
- In another instance, I changed a config from boolean with default "true" to integer slider with a min of 0 and max of 4 and default of 3, however the default in game is still "true" and the option appears as a boolean.
- I have tested with both version 2035 and version 2082. 
- Deleting the pipeline configuration file only results in the config options being put back to their "defaults".
- What happened in the second scenario:
Current: 
```
                auto_exposure: {
                    default: "3",
                    min: "0",
                    max: "4",
                    nameKey: "config.honey.name.auto_exposure",
                    descriptionKey: "config.honey.help.auto_exposure"
                },
```
Previous:
```
                auto_exposure: {
                    default: "true",
                    nameKey: "config.honey.name.auto_exposure",
                    descriptionKey: "config.honey.help.auto_exposure"
                },
```

**What you expected would happen**

- I expected the options to be updated accordingly, at least after a resource reload.

**What actually happened**

- The options did not update and instead reflect their previous versions.

**Logs and screenshots**
[latest.log](https://github.com/vram-guild/canvas/files/7342527/latest.log)

**Comment by ambrosia13** [comment]
Update: this is not just an issue on my side. Other devices downloading the shader for the first time are also affected by this.

**Comment by ambrosia13** [comment]
Workaround: I just remade the auto exposure option with a different name and it worked. I also changed the #ifdefs for the other options to #ifndefs because remaking the options was not fixing the problem.

**Comment by spiralhalo** [comment]
Can't reproduce this. Config type and default changed just fine without resource reload. Unless I'm interpreting it wrong?

https://user-images.githubusercontent.com/8444172/138837520-3d1bbfc7-01c6-47d9-9433-d78c8be75046.mp4

Maybe it's because you put quotation mark around numbers and boolean values? I'm not sure how that works in the first place, maybe JSON5 is _that_ lenient. But you shouldn't need to do that. Quotation marks are typically interpreted as textual strings.

**Comment by ambrosia13** [comment]
You're right, removing the quotation marks fixes it. 

I guess I just got confused since the [Pipeline Config Wiki](https://github.com/grondag/frex/wiki/Pipeline-Configuration) had booleans in quotation marks. It appears Canvas reads everything as true when the booleans are in quotes?

Anyway, sorry for the trouble.

**Comment by spiralhalo** [comment]
Interesting observation. It could be an issue with the wiki and Canvas itself. While I'm not super familiar with json5 I'm almost sure quotation mark will be interpreted as string (otherwise how would you encode an actual string that says "true"?) You're probably right that Canvas interprets string as a true boolean somehow. I'll look into it but still consider this particular issue resolved.
