### ISSUE TITLE
Certain blocks/chunks aren't rendered

### ISSUE THREAD

**Issue by supsm** [grondag/canvas#337]
**System Informatinon**

- Minecraft Version: 1.17
- Canvas Version: 1.0.2187
- Operating System: Windows 11
- Graphics Card: Nvidia 1660 Ti

**Other mods and versions installed**

<img width="1741" alt="image" src="https://user-images.githubusercontent.com/60897356/141246259-10e86bcc-32b2-4da8-a850-d22adb211ebb.png">

The mods aren't the issue though, I can reproduce without the mods

**How you triggered the behavior**

- start minecraft
- set pipeline to canvas dev or one with shadows
- set render distance to a relatively large amount (e.g. 16)
- log into multiplayer world
- turn around

**What you expected would happen**

- The world would render

**What actually happened**

- Nothing is rendered apart from what is initially seen

- Reloading chunks and resource packs helps a bit, but doesn't fix the issue
- Render distance 12 and 8 seem to be mostly ok

**Logs and screenshots**

https://user-images.githubusercontent.com/60897356/141245653-b8a72776-2346-4ed5-9382-6c0688497956.mp4

https://user-images.githubusercontent.com/60897356/141245641-7e16552c-e52b-4715-95ed-51b42f26b642.mp4

Log with error part:
```
[21:39:47] [Canvas Render Thread - 0/ERROR]: Unhandled error during rendering. Impact unknown.
java.lang.NullPointerException: Cannot read field "neighbors" because "region" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.63) ~[?:?]
	at grondag.canvas.terrain.region.NeighborRegions.getNeighbor(NeighborRegions.java:87) ~[canvas-fabric-mc117-1.17-1.0.2187.jar:?]
	at grondag.canvas.terrain.region.NeighborRegions.enqueueUnvistedShadowNeighbors(NeighborRegions.java:175) ~[canvas-fabric-mc117-1.17-1.0.2187.jar:?]
	at grondag.canvas.terrain.occlusion.TerrainIterator.iterateShadows(TerrainIterator.java:545) ~[canvas-fabric-mc117-1.17-1.0.2187.jar:?]
	at grondag.canvas.terrain.occlusion.TerrainIterator.run(TerrainIterator.java:232) ~[canvas-fabric-mc117-1.17-1.0.2187.jar:?]
	at grondag.canvas.terrain.util.DedicatedTerrainExecutor$Worker.run(DedicatedTerrainExecutor.java:107) [canvas-fabric-mc117-1.17-1.0.2187.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by wouu** [comment]
getting this error in 1.18 builds, seems to be regardless of render distance, happens after seconds instead of just after a while

**Comment by supsm** [comment]
Some additional information: render distances of 8 still don't render things that are very high or low. I'm not sure exactly how far this is, but it is between 64 and 192 blocks. Also, it does not happen in the nether, I have tried with 16 and 20 render distances. I will update on the end when I get to it.

**Comment by supsm** [comment]
The bug does not happen in the end, and higher y-values cause neighboring chunks to sometimes not render. I could "force" chunks to render by going down with freecam and reloading chunks. These new chunks will continue to be rendered until I change the render distance (reloading chunks and resourcepacks still render the chunks). At 8 chunks, I could only get it to render 32 blocks (192 to 160).

**Comment by wouu** [comment]
> getting this error in 1.18 builds, seems to be regardless of render distance, happens after seconds instead of just after a while

update on my claim, it seems like it only happens in custom dimensions for me curiously enough, the overworld/nether/end don't appear to be affected

**Comment by wouu** [comment]
i also notice that in my case the situation isn't as simple as certain chunks not rendering, it seems that when the error happens canvas entirely stops trying to render anything new onto the screen, resulting in weird things like this happening:
![2021-12-01_07 05 37](https://user-images.githubusercontent.com/89600701/144187821-fb636906-8dac-43ad-afe6-55255e7f11d2.png)
since my situation appears to be different than yours in some ways, and i'm getting it on a different version (mc 1.18 canvas 1.0.2230), i'm wondering if i should make a separate issue

**Comment by supsm** [comment]
I also get this issue sometimes, I believe this specifically has to do with the "cull backfacing terrain" option. I will update in a few days what happens to me in 1.18.

**Comment by supsm** [comment]
uh oh, it happens in singleplayer as well (1.18)

**Comment by supsm** [comment]
Just tried the new release (2249), singleplayer seems to be fixed. I don't really have anywhere I can test multiplayer on, but I will update if I find a server

**Comment by wouu** [comment]
> Just tried the new release (2249), singleplayer seems to be fixed. I don't really have anywhere I can test multiplayer on, but I will update if I find a server

yep, all seems to be working for me now as well.

**Comment by wouu** [comment]
if this issue is effectively fixed now, should it probably be closed or something?
