### ISSUE TITLE
Canvas Dev visual issues

### ISSUE THREAD

**Issue by istvanmate** [grondag/canvas#339]
First of all, big thanks for this mod! Awesome work!

**System Informatinon**

- Minecraft Version: 1.18pre4
- Canvas Version: 1.0.2220
- Operating System: Windows 11
- Graphics Card: 1050ti

**Other mods and versions installed**

- fabric-api-0.42.7+1.18
- betterdroppeditems-1.3.1-21w37a
- leaf-decay-1.3.0-1.17.1
- modmenu-3.0.0
- voicechat-fabric-21w44a-1.0.0

**How you triggered the behavior**

- tall and 2tall grass, flowers, I guess mushrooms affected by sunlight while being in the shadows
- dirt-grass contour shines in the shadows
- torch dynamic light is way too bright, further blocks receive the same amount of light that the close blocks

**What you expected would happen**
- tall and 2tall grass in the shadow should not be affected by sunlight
- torch dynamic light: light should be weaker overall, further blocks should receive less lighting than close blocks

**Logs and screenshots**
![image](https://user-images.githubusercontent.com/11715711/142459494-c1b523b3-a95d-4e33-9157-609c5d0770c0.png)
![image](https://user-images.githubusercontent.com/11715711/142459639-42dc57e2-30bc-4a7c-a60a-9896831dc497.png)
![image](https://user-images.githubusercontent.com/11715711/142460572-721c3002-d417-4764-9796-d6000fd05a7a.png)

**Comment by grondag** [comment]
Thank you for the report. The Dev pipeline is work-in-progress code and will often have visual flaws.  The lighting model is mostly garbage - it was most recently use for testing shadow maps.

A future version of Canvas will have a better, supported pipeline with shadow map and other "advanced features."

**Comment by istvanmate** [comment]
No problem, feel free to relocate or delete this post. I just wanted to help by contributing.
