### ISSUE TITLE
Block Fog affect item rendering

### ISSUE THREAD

**Issue by SteveKunG** [grondag/canvas#340]
**System Information**

- Minecraft Version: 1.17.1
- Canvas Version: 1.0.2201
- Operating System: Windows 10
- Graphics Card: GTX 1050 Ti

**Other mods and versions installed**

![image](https://user-images.githubusercontent.com/6128413/142715615-0ee093c5-33c5-4ed7-954a-33b5f8bf3f5f.png)

**How you triggered the behavior**

- Grab some items and put into hotbar
- Go inside water/lava/powder snow

**What you expected would happen**

- Items in hotbar should render properly

**What actually happened**

- Items rendering affected by block fog

**Logs and screenshots**
![2021-11-20_12 26 50](https://user-images.githubusercontent.com/6128413/142715596-51871991-03a6-4c0f-afa2-db18846bd49f.png)
![2021-11-20_12 26 53](https://user-images.githubusercontent.com/6128413/142715599-9c1bde84-98ae-4a6d-a02b-ff4ef1a297bb.png)
![2021-11-20_12 28 24](https://user-images.githubusercontent.com/6128413/142715600-92572b0e-5e97-42ba-8dbd-ceb7166ba2f9.png)

**Comment by grondag** [comment]
Fixed by https://github.com/vram-guild/frex/commit/d797ef0c2551bc6d7033185b7af24a516cb06322

**Comment by supsm** [comment]
This does not appear to be completely fixed, certain items (such as beds, shields) with a 3d item icon still suffer from this issue.  
Here is an image of a shield underwater, with other blocks for reference
<img width="134" alt="image" src="https://user-images.githubusercontent.com/60897356/185011746-a30fa00e-342a-4e29-847c-b74c37ff4e7c.png">

**Comment by spiralhalo** [comment]
> This does not appear to be completely fixed, certain items (such as beds, shields) with a 3d item icon still suffer from this issue. Here is an image of a shield underwater, with other blocks for reference <img alt="image" width="134" src="https://user-images.githubusercontent.com/60897356/185011746-a30fa00e-342a-4e29-847c-b74c37ff4e7c.png">

Typical shield being custom rendered item. Chest and trident might be affected as well.

**Comment by supsm** [comment]
I don't think they should be affected, chest is an isometric rendering (like the other blocks), and trident is a 2d item texture

**Comment by spiralhalo** [comment]
I'm not sure what you're trying to argue. It's a bug.
