### ISSUE TITLE
Tropical Fish tail texture UVs issue

### ISSUE THREAD

**Issue by SteveKunG** [grondag/canvas#342]
**System Information**

- Minecraft Version: 1.17.1
- Canvas Version: 1.0.2201
- Operating System: Windows 10
- Graphics Card: GTX 1050 Ti

**Other mods and versions installed**

![image](https://user-images.githubusercontent.com/6128413/142715615-0ee093c5-33c5-4ed7-954a-33b5f8bf3f5f.png)

**How you triggered the behavior**

- Summon tropical fish
- Searched for Kob model

**What you expected would happen**

- Tropical Fish should look normal

**What actually happened**

- Tropical Fish Kob variant tail rendering bug

**Logs and screenshots**
- Vanilla
![2021-11-20_12 37 54](https://user-images.githubusercontent.com/6128413/142715904-9fbe2811-106d-4802-a2e8-0adfa6feb9c2.png)
- Canvas
![2021-11-20_12 40 12](https://user-images.githubusercontent.com/6128413/142715906-709e544f-ce0a-4d46-8e9c-e98440bc4a4c.png)

**Comment by spiralhalo** [comment]
Thank you for your detailed report. This is now fixed in 7db0564b1ec1c1b63d0e7b2147bf062fbb9de95c
