### ISSUE TITLE
No Entity Shadows

### ISSUE THREAD

**Issue by supsm** [grondag/canvas#363]
**System Informatinon**

- Minecraft Version: 1.18.1
- Canvas Version: 1.0.2281
- Operating System: Windows 11
- Graphics Card: 1660 Ti

**Other mods and versions installed**

**How you triggered the behavior**

- start minecraft
- summon an entity

**What you expected would happen**

- There would be entity shadows (the circle)

**What actually happened**

- There are no shadows

**Logs and screenshots**
![image](https://user-images.githubusercontent.com/60897356/148313802-acbcb0d7-97bc-4072-8b76-236257ddde1c.png)

**Comment by spiralhalo** [comment]
Did you turn on entity shadows in video settings? Your issue didn't specify this information.

![image](https://user-images.githubusercontent.com/8444172/148317971-393b64b4-8447-42b6-8a2c-f49c153bc5ee.png)

**Comment by supsm** [comment]
yes, sorry

**Comment by spiralhalo** [comment]
It looks like the entity shadows disappear when looking at certain direction or due to some unknown state change (like https://github.com/spiralhalo/LumiLights/issues/68 but different).
