### ISSUE TITLE
Candles don't work

### ISSUE THREAD

**Issue by supsm** [grondag/canvas#364]
**System Informatinon**

- Minecraft Version: 1.18.1
- Canvas Version: 1.0.2281
- Operating System: Windows 11
- Graphics Card: nvidia1660 ti

**Other mods and versions installed**

lumi 0.40-snapshot10

**How you triggered the behavior**

- start minecraft
- place candle
- light it

**What you expected would happen**

- particles would appear

**What actually happened**

- nothing

**Logs and screenshots**
![2022-01-05_18 23 02](https://user-images.githubusercontent.com/60897356/148323867-af8fdd52-a60e-409d-be2c-a01845c9f094.png)
the front row is lit, back row isn't
yes I know it's lumi, but I checked on canvas standard too... lumi just looks nicer for screenshots

**Comment by spiralhalo** [comment]
They work for me

![image](https://user-images.githubusercontent.com/8444172/149168826-34d2a7ae-8fd5-4ddd-b794-22bbc9b78bd3.png)

**Comment by supsm** [comment]
Huh… what version is that

**Comment by spiralhalo** [comment]
My bad, 1.0.2282 (github latest) on 1.18.1

**Comment by supsm** [comment]
I'll give it a try later, it might be one of my other million mods

**Comment by supsm** [comment]
idk it works now
