### ISSUE TITLE
Canvas leaves matrix stack in a different state compared to Vanilla renderer

### ISSUE THREAD

**Issue by zml2008** [grondag/canvas#366]
**System Information**

- Minecraft Version: 1.18.1
- Canvas Version: 1.0.2302
- Operating System: Windows 10
- Graphics Card: Nvidia RTX 2060

**Other mods and versions installed**

- Fabric API 0.46.1
- worldedit 7.2.9-SNAPSHOT+6083-ab31481
- worldeditcui 1.18.1+01-SNAPSHOT

**How you triggered the behavior**

- enter singleplayer world, make a selection with WorldEdit

**What you expected would happen**

- Overlay would be drawn in world space, unaffected by the camera

**What actually happened**

- Overlay position is affected by the camera

**Logs and screenshots**
See a quick recording:

https://user-images.githubusercontent.com/629092/151744401-d7071ee9-2056-4bc6-a1b2-bc13087a188d.mp4

WECUI uses fabric API's world render events for its rendering hooks -- see here: https://github.com/EngineHub/WorldEditCUI/blob/ef79e87951919a2ee9341e75e821e6f6a0231651/src/main/java/org/enginehub/worldeditcui/fabric/FabricModWorldEditCUI.java#L91

**Comment by spiralhalo** [comment]
Thank you for reporting this! Should be fixed in ccb05b25d2676dbd08df1c5fe806cb62961fe784
