### ISSUE TITLE
Canvas (1.0-2306) crashes on 1.18.2.

### ISSUE THREAD

**Issue by Kichura** [grondag/canvas#370]
**System Information**

- Minecraft Version: 1.18.2
- Canvas Version: 1.0-2306
- Operating System: Linux
- Graphics Card: Radeon 6600 XT

**Other mods and versions installed**

- Fabric API 0.47.8+1.18.2

**How you triggered the behavior**

- Open up any client with latest canvas build on 1.18.2,
- Try to load into any world,
- Expect a crash.

**What you expected would happen**

- Canvas continues to operate properly without issues.

**What actually happened**

- Canvas ends up crashing instead on any world due to broken classes.

**Logs and screenshots**
- [The crash dump can be found here,](https://pastebin.com/raw/9CAsBGBW)
- Screenshots not added here as i am unable to produce any.

**Comment by supsm** [comment]
Can confirm (Windows, 1660 Ti, same canvas version, fabric api 0.47.9+1.18.2). The world appears to load normally and the loading icon appears, but then it just crashes

**Comment by Kichura** [comment]
Closing this as it has been fixed in commit 2307 since.
