### ISSUE TITLE
Colored Lights

### ISSUE THREAD

**Issue by yyz729** [grondag/canvas#375]
I noticed that the handheld light is colored,  is the block in the world okay?

**Comment by Reeses-Puffs** [comment]
Worldspace colored lights aren't possible at the moment due to the way Canvas's lighting system works. This is planned to be possible in the future. The reason handheld lights are colored is because it is easy to get information about what items are being held.

**Comment by yyz729** [comment]
thanks

**Comment by supsm** [comment]
If you are interested, [Forget-Me-Not](https://github.com/Poisoned-Honey/ForgetMeNot-Shaders) has colored block lights with global illumination, though it is rather expensive. It's also very pretty regardless, might be worth a try :)
