### ISSUE TITLE
Some options in Canvas config are named incorrectly

### ISSUE THREAD

**Issue by ambrosia13** [grondag/canvas#378]
**System Information**

- Minecraft Version: 1.18.2 
- Canvas Version: unofficial build released by spiralhalo, canvas-fabric-mc118-1.0.2324-UNOFFICIAL (https://discord.com/channels/614624415631671316/614625541114298397/964175657523347616)

![canvas1](https://user-images.githubusercontent.com/79555621/169624037-f87f4202-8b2d-437b-882d-8075f4951733.png)
![canvas2](https://user-images.githubusercontent.com/79555621/169624043-8f117ca9-427e-49ba-ad64-c75c18c9bc60.png)

**Comment by supsm** [comment]
why did you close it without explaination

**Comment by supsm** [comment]
nvm i'm smart
