### ISSUE TITLE
Magma blocks rendering issue.

### ISSUE THREAD

**Issue by calloatti** [grondag/canvas#38]
MC/Fabric 1.14.4 (no Fabric API)

![2019-07-30_20 34 01](https://user-images.githubusercontent.com/12817862/62188969-392e6280-b344-11e9-9cc0-2bbca520d39d.png)

MC/Fabric 1.14.4
fabric-api-0.3.0+build.207
canvas-0.7.5+build.340

![2019-07-30_20 31 29](https://user-images.githubusercontent.com/12817862/62188989-451a2480-b344-11e9-89d8-8b793981bb6a.png)

**Comment by grondag** [comment]
Now released on Curse: https://www.curseforge.com/minecraft/mc-mods/canvas-renderer/files/2756313
