### ISSUE TITLE
All blocks are black

### ISSUE THREAD

**Issue by BD103** [grondag/canvas#387]
**System Information**

- Minecraft Version: 1.19
- Canvas Version: 1.0.2410
- Operating System: Windows 64 bit
- Graphics Card: Integrated I think? Not sure how to check it

**Other mods and versions installed**

- Fabric API 0.57.0
- Mod Menu 4.0.3
- Logical Zoom 0.0.15

**How you triggered the behavior**

- Start Minecraft
- Open singleplayer world
- Reload resource packs (F3-T)
- See bug

**What you expected would happen**

- I expected all of the blocks to properly display

**What actually happened**

- All of the blocks are black, only the sky is visible.

**Logs and screenshots**

![Rendering bug](https://user-images.githubusercontent.com/59022059/178642257-a2644f19-c05d-4ade-986b-eb497ebbcf9f.png)

I did notice a specific error that says "Failed to load Narrator libraries" and "Unable to load library 'SAPIWrapper_x86'".

[See the logs here...](https://paste.ee/p/B7wz4)

I'm guessing I'm probably doing something silly, so I apologize if there is a clear solution that I haven't tried. Thank you for helping!

**Comment by supsm** [comment]
Sorry for the late response, but you can check the graphics card from the F3 debug screen. Mostly we are just interested about the vendor (intel, amd, or nvidia) so we can debug the issue further. You could also try switching to a different pipeline in canvas settings (and switching back).

**Comment by BD103** [comment]
It's been about a year since I opened this issue. I think I'm going to close it as stale, and I'll re-open it if I ever encounter the issue again.

Thank you, and have a good day.
