### ISSUE TITLE
Crash with BYG

### ISSUE THREAD

**Issue by clmc99** [grondag/canvas#388]
**System Information**

- Minecraft Version: 1.19
- Canvas Version: 1.0.2410
- Operating System: Windows 11
- Graphics Card: Nvidia GeForce GTX 1660 Ti
- CPU: Intel i7-9750HF 2.60 GHz
- RAM: 16 GB

**Other mods and versions installed**

- Fabric API 0.57.0
- Oh The Biomes You'll Go 2.0.0.7
- TerraBlender 2.0.0.120

**How you triggered the behavior**

- put Fabric API, Canvas Renderer, BYG, and TerraBlender in mods folder
- start Minecraft
- did not run into creeper, cannot enter world to encounter creeper

**What you expected would happen**

- Game loads normally

**What actually happened**

- Red loading screen appears, loading bar goes most of the way, leading me to believe that the game is about to open normally; game crashes after a bit in this state

**Logs and screenshots**
[JVM error log](https://github.com/vram-guild/canvas/files/9105267/canvas-byg-jvm-error.log)
[Game log](https://github.com/vram-guild/canvas/files/9105269/canvas-byg-crash.log)

**Comment by supsm** [comment]
can't reproduce with canvas 1.0.2503, byg 2.0.0.13, terrablender 2.0.1.136 (1.19.2). probably has been fixed somewhere along the way
