### ISSUE TITLE
Broken transparency in materials that (?) write to solid framebuffer as well as inventory

### ISSUE THREAD

**Issue by ambrosia13** [grondag/canvas#394]
**System Information**

- Minecraft Version: 1.19.2
- Canvas Version: 2480
- Operating System: Windows
- Graphics Card: RTX 3060

**Other mods and versions installed**

- fabric-api-0.62.0+1.19.2
- canvas-fabric-mc119-1.0.2480

**How you triggered the behavior**

- start minecraft
- log into singleplayer world
- look at any cutout item, in inventory or in world

**What you expected would happen**

- Transparency/cutout material works as intended

**What actually happened**

- Material is black where it is supposed to be discarded
- Only an issue in 1.19.2, I can confirm that this does not happen on my 1.19.0 profile

**Logs and screenshots**

[latest.log](https://github.com/vram-guild/canvas/files/9731319/latest.log)
![image](https://user-images.githubusercontent.com/79555621/194485041-6796d5c0-c8b3-4904-ba05-7d2f0c361048.png)
![image](https://user-images.githubusercontent.com/79555621/194485137-2c29251d-c052-4003-91ca-033d1baa7fe5.png)
![image](https://user-images.githubusercontent.com/79555621/194485364-0dc379c1-6bf8-4644-8188-1fa88833090a.png)

**Comment by supsm** [comment]
issue can be reproduced with 3050 and 3070 Ti (the collection is almost complete :tinypotato:)

**Comment by ambrosia13** [comment]
Version 2477 works as expected

**Comment by supsm** [comment]
Also, some "item backgrounds" are green or white instead of black

**Comment by supsm** [comment]
hmm... this is only made worse by release 2487, which straight up crashes when a chest item is being rendered.  
To reproduce:
- open inventory in creative
OR
- /give yourself a chest with an empty hotbar (I haven't tested with other items yet)

crash reports:
[crash-2022-10-13_19.32.26-client.txt](https://github.com/vram-guild/canvas/files/9781993/crash-2022-10-13_19.32.26-client.txt)
[crash-2022-10-13_19.30.20-client.txt](https://github.com/vram-guild/canvas/files/9781994/crash-2022-10-13_19.30.20-client.txt)

**Comment by spiralhalo** [comment]
> hmm... this is only made worse by release 2487, which straight up crashes when a chest item is being rendered. To reproduce:
> 
>     * open inventory in creative
>       OR
> 
>     * /give yourself a chest with an empty hotbar (I haven't tested with other items yet)
> 
> 
> crash reports: [crash-2022-10-13_19.32.26-client.txt](https://github.com/vram-guild/canvas/files/9781993/crash-2022-10-13_19.32.26-client.txt) [crash-2022-10-13_19.30.20-client.txt](https://github.com/vram-guild/canvas/files/9781994/crash-2022-10-13_19.30.20-client.txt)

Should be fixed in https://github.com/vram-guild/canvas/commit/957b8cf10961b37345579d6d5ecd59358d99920e

Original issue was fixed in https://github.com/vram-guild/frex/commit/09d4e5196dd9d05ba3d3aca91cd78562ed59a149
