### ISSUE TITLE
Canvas causes graphics options can not to be set, causing compatibility issues

### ISSUE THREAD

**Issue by AugFUZE** [grondag/canvas#399]
**System Information**

- Minecraft Version: 1.18.2
- Canvas Version: canvas-fabric-mc118-1.0.2397
- Operating System: window 10
- Graphics Card:GTX1660

**Other mods and versions installed**

- fabric-0.14.9
- lumi-v0.41

**Description of the problem**
- The canvas mod replaces the original "Video Setting"-"Graphics" option after loading.
and lock the graphic quality to "Fabulous! ”

- This will cause some contents of some mods to not work properly.

- For example, block “gear” in "create mod" cannot be rendered in the "Fabulous! "Graphic quality option.

**Comment by ambrosia13** [comment]
This is intended. Pipelines can either be set to fabulous or fancy graphics. Use "Canvas Basic" for fancy graphics

**Comment by AugFUZE** [comment]
> This is intended. Pipelines can either be set to fabulous or fancy graphics. Use "Canvas Basic" for fancy graphics

How to set to fancy graphics？I don't see the relevant options.

**Comment by ambrosia13** [comment]
Switch pipeline to canvas basic. The pipeline selection is at the very top of the screen when you click the canvas button.

**Comment by AugFUZE** [comment]
> Switch pipeline to canvas basic. The pipeline selection is at the very top of the screen when you click the canvas button.

The problem remains...
But when I removed the canvas mod.
The rendering of the gear is back to normal.
Even the graphic quality is fabulous.
So this should be a mod compatibility issue?

**Comment by supsm** [comment]
Yes, this seems to be a rendering compatibility issue. If you could post screenshots or logs, as well as the mods used, that would be helpful

**Comment by supsm** [comment]
I know that #404 is technically newer, but it contains more relevant information so this will be closed. As mentioned above, fabulous and fancy are by designed to be set by the pipeline and is not meant to be toggleable directly.
