### ISSUE TITLE
Unable to render some blocks/machine parts from Create

### ISSUE THREAD

**Issue by ZZZank** [grondag/canvas#404]
**System Information**

- Minecraft Version: 1.18.2
- Canvas Version: canvas-fabric-mc118-1.0.2397
- Operating System: windows11
- Graphics Card: AMD radeon graphics (Vega 8 actually)

**Other mods and versions installed**

- fabric-0.14.10
- fabricAPI-0.67.1
- Create 0.5i

**How you triggered the behavior**

- start minecraft
- log into any world
- place any Create machine that is gear or shaft, or has gear or shaft as part of the machine
- see those parts missing

**What you expected would happen**

- render those gears and shafts.

**What actually happened**

- saw nothing.

**Logs and screenshots**
screenshots:
![2023-02-11_14 57 00](https://user-images.githubusercontent.com/47418975/218245455-96eae35e-aede-4433-903d-a43ae6d47770.png)

[latest.log](https://github.com/vram-guild/canvas/files/10712833/latest.log)
after getting this log file, I turned on most of those debug option, and got logs, atlas, and some other stuff.
[moreDebug.zip](https://github.com/vram-guild/canvas/files/10712837/moreDebug.zip)

**Comment by spiralhalo** [comment]
Thanks for the report. Create compatibility was added in recent releases for 1.18.2 and 1.19.2 on May 2023.

If this issue persists, try going into Flywheel setting (next to Create setting in the GUI) and changing the "Backend" to "OFF".

If the issue persists after that, feel free to re-open the issue with relevant additional information.
