### ISSUE TITLE
Mod is Incompatible with Chisels n Bits libarary mod Saecularia Caudices

### ISSUE THREAD

**Issue by AlphaMode** [grondag/canvas#407]
**System Information**

- Minecraft Version: 1.19.2
- Canvas Version: mc119-1.0.2503
- Operating System: Kubuntu 22.04
- Graphics Card: NVIDIA GeForce RTX 3070

**Other mods and versions installed**

- AOF 6 (modpack without sodium)
- Canvas
- 
![image](https://user-images.githubusercontent.com/26313415/221043408-fa1febbd-2324-40fd-bdde-73ce8ca8b5c7.png)

Linking issue [https://github.com/Communi-Suggestu/Saecularia-Caudices/issues/4](https://github.com/Communi-Suggestu/Saecularia-Caudices/issues/4)

**Comment by supsm** [comment]
Can reproduce. Fortunately it is also reproducible with only canvas and chisels n bits, so you don't need to wait for the entire aof modpack to load when testing

**Comment by supsm** [comment]
should be fixed by #408
