### ISSUE TITLE
No entity shadows on 1.19.3 branch for all shadow pipelines

### ISSUE THREAD

**Issue by ambrosia13** [grondag/canvas#410]
**System Information**

- Minecraft Version: 1.19.3
- Canvas Version: canvas-fabric-mc119-1.0.2515-SNAPSHOT
- Operating System: Windows
- Graphics Card: Nvidia RTX

**Other mods and versions installed**

None, reproducible with just Canvas

**How you triggered the behavior**

- start minecraft
- log into singleplayer world
- no entity shadows

**What you expected would happen**

- Entity shadows

**What actually happened**

- No entity shadows

**Logs and screenshots**
[log.](https://mclo.gs/bivjQwl)
![screenshot](https://cdn.discordapp.com/attachments/839653070622818337/1082140138320183376/2023-03-05_19.13.55.png)

**Comment by spiralhalo** [comment]
I can't reproduce it. Did you happen to turn entity shadows off in video options?

Here is an all pipeline screenshot buffet.

![image](https://user-images.githubusercontent.com/8444172/223021907-33fd1a74-4061-4667-b412-51417556985e.png)

**Comment by ambrosia13** [comment]
Ah. I didn't realize that turning off the circular entity shadows also disables entity shadowmap shadows. My mistake.
