### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION when reloading resource packs

### ISSUE THREAD

**Issue by macbrayne** [grondag/canvas#411]
**System Information**

- Minecraft Version: 1.19.2
- Canvas Version: 1.0.2503
- Operating System: Windows 10 Build 19045.2604
- Graphics Card: AMD Vega 6 Graphics (iGPU)
- CPU: AMD Ryzen 4600U
- Driver Version: 22.11.2

**Other mods and versions installed**

- loader: fabric 0.14.17

**How you triggered the behavior**

- start minecraft
- select abstract shader
- add "abstract" resource pack in Minecraft settings

**What you expected would happen**

- game should reload resource packs

**What actually happened**

- game crashes

**Logs and screenshots**
[latest.log](https://github.com/vram-guild/canvas/files/10949462/latest.log)
Crash (from main menu): [hs_err_pid16996.log](https://github.com/vram-guild/canvas/files/10949458/hs_err_pid16996.log)
Different crash (in-game), also when reloading resource packs: [hs_err_pid16724.log](https://github.com/vram-guild/canvas/files/10949459/hs_err_pid16724.log)

**Comment by fewizz** [comment]
Known issue. I'll try to fix it later.

**Comment by fewizz** [comment]
Btw i can't reproduce it with driver version `23.3.1`

**Comment by macbrayne** [comment]
Here a crash with driver version `23.2.2` 
[hs_err_pid22492.log](https://github.com/vram-guild/canvas/files/10952436/hs_err_pid22492.log)
[latest.log](https://github.com/vram-guild/canvas/files/10952437/latest.log)
...and `23.3.1`:
[hs_err_pid13024.log](https://github.com/vram-guild/canvas/files/10952477/hs_err_pid13024.log)

**Comment by fewizz** [comment]
Please, try this one: https://drive.google.com/file/d/1viXSyoH90-3RkQR8hubLMKCWmntiHk1r/view?usp=sharing

**Comment by macbrayne** [comment]
Seems to work fine now 👍
