### ISSUE TITLE
Physics Mod doesn't show ragdolls or break particles.

### ISSUE THREAD

**Issue by lumithespoofy64** [grondag/canvas#415]
**System Information**

- Minecraft Version: 1.19.2
- Canvas Version: v1.0.2503
- Operating System: Windows 10
- Graphics Card: NVIDIA GeForce RTX 2070 SUPER

**Other mods and versions installed**

- fabric-1.2.3
- lumi-4.5.6
- canvas-fabric-mc119-1.0.2503
- physics-mod-pro-v147-fabric-1.19.2

**How you triggered the behavior**

- Start minecraft.
- log into singleplayer or multiplayer world.
- Kill a mob or break a block.

**What you expected would happen**

- Mob would ragdoll and block would have pieces of itself on the ground.

**What actually happened**

- No block pieces and no ragdoll. Even if I turned off the physics.

**Logs and screenshots**
It is not a crash. And I can't get a gif for this.

**Comment by supsm** [comment]
Related (duplicate?): #209, #217
