### ISSUE TITLE
Crash at startup when using with Custom Machinery

### ISSUE THREAD

**Issue by ZZZank** [grondag/canvas#429]
**System Information**

- Minecraft Version: 1.18.2
- Canvas Version: canvas-fabric-18.2.2616
- Operating System: win11
- Graphics Card: AMD Vega8

**Other mods and versions installed**

- fabric-0.14.21
- fabric API-0.76.0
- CustomMachinery-fabric-1.18.2-0.8.3
- architectury-4.11.89-fabric (dependency of CM)
- cloth-config-6.4.90-fabric (dependency of CM)
- TechReborn-5.2.1 (dependency of CM)

**How you triggered the behavior**

- start minecraft
- crash

**Logs and screenshots**

[crash-2023-06-27_19.09.35-client.txt](https://github.com/vram-guild/canvas/files/11881284/crash-2023-06-27_19.09.35-client.txt)

I have some knowledge about mixin, and I found a cretain part in crash report that's very likely to be the reason: 
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_778::custommachinery$getLightEmission with priority 1000 cannot inject into net/minecraft/class_778::method_3374(Lnet/minecraft/class_1920;Lnet/minecraft/class_1087;Lnet/minecraft/class_2680;Lnet/minecraft/class_2338;Lnet/minecraft/class_4587;Lnet/minecraft/class_4588;ZLjava/util/Random;JI)Z merged by grondag.canvas.mixin.MixinModelBlockRenderer with priority 1000 [PREINJECT Applicator Phase -> custommachinery.fabric.mixins.json:ModelBlockRendererMixin from mod custommachinery -> Prepare Injections ->  -> redirect$zfh000$custommachinery$getLightEmission(Lnet/minecraft/class_2680;Lnet/minecraft/class_1920;Lnet/minecraft/class_1087;Lnet/minecraft/class_2680;Lnet/minecraft/class_2338;)I -> Prepare]
`

Also, the same issue : https://github.com/Frinn38/Custom-Machinery/issues/94

**Comment by supsm** [comment]
Hi, it seems that my pull request #408 for 1.19 (which fixes this issue) has only been merged into 1.18 branch in the latest commit. Could you try compiling it yourself? And @spiralhalo could you consider releasing another 1.18.2 release?

**Comment by ZZZank** [comment]
> Could you try compiling it yourself?

I don't know how to, so I might better just wait for a new release.

**Comment by supsm** [comment]
New release 18.2.2621 is out, maybe give that a shot

**Comment by spiralhalo** [comment]
I tested the new release myself. Thanks for the report

On a side note, Custom Machinery has a rendering issue relating to matrix state, but this is confirmed reproducible without Canvas thus is unrelated to Canvas.

**Comment by Frinn38** [comment]
@spiralhalo Would you mind giving some infos about this rendering issue of CM, either on the github or the discord ?

**Comment by supsm** [comment]
@Frinn38 discussion of other issues should be done on canvas or a separate Github issue for better bookkeeping.
