### ISSUE TITLE
(1.20) Incompatible with any mod modifying MixinItemRenderer

### ISSUE THREAD

**Issue by Syclusion** [grondag/canvas#436]
Crashes instantly with any mod that changes or adds its own. 

Tested with geckolib, azurelib, portinglib and I'm certain MixinItemRenderer is the culprit, as disabling it in the canvas jar fixes the issue but leads to many more. Strangely this issue is nonexistent on the 1.19 version

**Comment by spiralhalo** [comment]
6ce75aea89209e3eca20bd18c0d98a45f1c23435 fixes the crashes.
de9702037133a3f011a0abb02274fa36e521f825 adds azurelib and geckolib compatibility.

Thanks for reporting!
