### ISSUE TITLE
Request: compatibility with Light Overlay ?

### ISSUE THREAD

**Issue by 5l4y3r-burrito** [grondag/canvas#45]
hello i am using 2 of your other mods: facility and exotic blocks. i love these mods but they have canvas dependency so i must also use this mod. the only problem is while using canvas render mod then the light overlay mod does not work
link to light overlay mod (https://www.curseforge.com/minecraft/mc-mods/light-overlay)
there is no crash but i would love a way to see the light level while also using canvas, so if theres any way that could be possible or if it already is i would love to know! <3

**Comment by grondag** [comment]
Hmmm, those mods should *not* require canvas.   They should work fine with the default Fabric renderer.   Have you tried them without Canvas and if so did they give you an error?

That said,  I agree light overlay is a useful mod and it would be good to have compatibility so I will see what can be done for that.   Thank you for reporting the issue.

**Comment by 5l4y3r-burrito** [comment]
yes when i remove canvas then my single player world says "saving world" as soon as the terrain generation gui finishes, and never makes it into the actual game. also does not crash so i have to force quit it and this also happened when i tried to make a new world.
but really its not that i don't want to use canvas so if you do find a way to make the markers show up that would be best!
thank you for the quick reply!

**Comment by grondag** [comment]
The light layer fix is uploaded to CurseForge and should be visible soon but I was not able to reproduce the issues with Exotic Blocks or Facility.  If you could post an issue for either of those mods with your log after the problem happens that may help me track it down.

Thanks again for the useful info. Glad you are enjoying the mods.

**Comment by 5l4y3r-burrito** [comment]
worked like a charm!!!
idk how to open log window in multimc lol, it only pops up after a crash. is there a hotkey or something? i couldn't find how on google 😅

**Comment by 5l4y3r-burrito** [comment]
oh wait i deleted a couple mods and got it to crash... going to post the log on facility in a minute

**Comment by shedaniel** [comment]
Thanks for implementing this <3
