### ISSUE TITLE
BER persists after the BE is broken

### ISSUE THREAD

**Issue by Azzyypaaras** [grondag/canvas#47]
![image](https://user-images.githubusercontent.com/20349662/85937683-9ff92a80-b8cb-11ea-8e29-2ab194b13d53.png)

When a block entity is placed, F3+A is pressed, and said entity is then broken, its BER persists until F3+A is pressed again.

**Comment by grondag** [comment]
Reproduced.  Think I have an idea of what is happening and should be an easy fix.
