### ISSUE TITLE
Lighting in complex models is acting funky

### ISSUE THREAD

**Issue by Azzyypaaras** [grondag/canvas#48]
![image](https://user-images.githubusercontent.com/20349662/85942728-bbc2f780-b8f0-11ea-8a82-66f0af9eaadc.png)
![image](https://user-images.githubusercontent.com/20349662/85942735-c54c5f80-b8f0-11ea-9ad1-f9fe407154ad.png)
![image](https://user-images.githubusercontent.com/20349662/85942746-d5fcd580-b8f0-11ea-919f-74245b380a59.png)
They really do be in on that funk

**Comment by grondag** [comment]
The images are very dark and it isn't clear where/what the problem is. Could you please elaborate?

**Comment by Azzyypaaras** [comment]
The lighting in more complex models occasionally breaks on various faces. The issue is inconsistent and seems to fall into the lovely category of "only arises when you are not trying to screenshot it". I did manage to get a clearer shot here.
![image](https://user-images.githubusercontent.com/20349662/85956243-4552e380-b94a-11ea-80ce-0430a9c3bcf7.png)
As you can see, the bottom face here is far darker than it should be. Notably, this only ever seems to happen in one direction at once.

**Comment by grondag** [comment]
Hmmm, is AmbientOcclusion shading disabled on the model or on the material for that quad?

**Comment by Azzyypaaras** [comment]
I am not particularly experienced with the sort of stuff. But given that this is just a plain json model and given that that this does not have any shaders applied to it. Probably no.

**Comment by grondag** [comment]
If you don't have `"ambientocclusion": false` in the model JSON it will be enabled.  Try adding that or confirming it is there.

My guess is that it is getting shaded by the block below it, because it is "close" to that face.  The Vanilla lighting model isn't great at shading fine detail like that, especially internal faces.

**Comment by Azzyypaaras** [comment]
Nope, it is disabled. I should note that I have only seen this issue with Canvas installed.

**Comment by grondag** [comment]
Interesting.  Can I get a copy of the JSON model?

**Comment by Azzyypaaras** [comment]
[fruitpress.zip](https://github.com/grondag/canvas/files/4848354/fruitpress.zip)

**Comment by grondag** [comment]
Tried it and unable to reproduce with the model alone.  Will need full code for block.
