### ISSUE TITLE
VRAM Memory Leak

### ISSUE THREAD

**Issue by RolledR** [grondag/canvas#49]
Not sure what else to call it. As I play, my VRAM slowly fills up.

Running Manjaro 20.0.3
Kernel 20.5.6.16-1-MANJARO
Nvidia 2070 Super
Using proprietary Nvidia drivers, version 440.
Java 14

New Minecraft 1.16.1 instance, latest fabric loader (0.8.9+build.203), fabric api (0.14.1+build.372-1.16), and Canvas (1.0.728)
No other mods.
Default settings.

It seems like it happens as more blocks / chunks are loaded.
Returning to the main menu doesn't free the memory, Minecraft has to be entirely closed.

Here's the [log](https://hastebin.com/uqaviquqit.sql), but there's nothing interesting as far as I can see. Ignore the java arguments, I was testing something else and forgot to disable them.

Not that it helps much, but **Screenshots**:

Minecraft VRAM Usage
![Minecraft Instance VRAM Usage](https://user-images.githubusercontent.com/54372977/86400957-5196b380-bc5e-11ea-9d4a-100e33a8f52d.png)
Total VRAM Usage
![Total VRAM Usage](https://user-images.githubusercontent.com/54372977/86400985-5c514880-bc5e-11ea-8c8f-de48a9048fd6.png)

**Comment by grondag** [comment]
Thank you for the useful issue report.  I'm probably not tearing down some buffer allocations somewhere.   Will have a look.
