### ISSUE TITLE
Light Smoothing has issues with slabs

### ISSUE THREAD

**Issue by bigdaddybart** [grondag/canvas#5]
Demonstration (option toggled off/on): https://imgur.com/a/8TnhwHz

Issue doesn't occur when one of the slabs is broken: https://imgur.com/a/84xZHui

**Comment by grondag** [comment]
FYI - fix for this will wait for v0.7 or later because it will be handled when smooth lighting is redone to handle colored lighting.

**Comment by grondag** [comment]
Suspended for now - likely to replace entire lighting method soonish
