### ISSUE TITLE
GPU temperature

### ISSUE THREAD

**Issue by Vixtron** [grondag/canvas#50]
I tested the latest build `canvas-mc116-1.0.743` and recorded high gpu temperature with bloom enabled.
I limited it to 120fps and it runs at ~60C

GPU: RX 580

![Taskmgr_JDghKhOpG0](https://user-images.githubusercontent.com/22355590/86500970-37abbc80-bd95-11ea-8272-ad5ecc5b0d34.png)

![Taskmgr_TOnC4w1NNH](https://user-images.githubusercontent.com/22355590/86500975-472b0580-bd95-11ea-8019-8897ac7a3ba0.png)

![javaw_MX8yjjKqgT](https://user-images.githubusercontent.com/22355590/86500973-43977e80-bd95-11ea-8439-b47aa337a466.jpg)

**Comment by grondag** [comment]
Next build will have a much faster bloom algorithm that hopefully won't start a fire.

**Comment by grondag** [comment]
Should be fixed in latest build posted in releases. Please reopen if not.
