### ISSUE TITLE
Color Depth Render Error in Resource Pack

### ISSUE THREAD

**Issue by T0paz** [grondag/canvas#51]
I just built canvas to test out the bloom shaders, and I found that with the [Lithos resource pack](https://www.curseforge.com/minecraft/texture-packs/lithos-core-32x-1-6-1-11-complete/files), the Shroomlight animated texture renders with far fewer colors than it should. In the attached image, you can see what the block looks like under the canvas renderer, and what it looks like rendered in hand/as an entity. I'm pretty sure this has to do with some Lithos textures having reduced color to save space in the pack, but I can't see anything immediately suspect when I open up the textures in GIMP.

[Image of the issue.](https://cdn.discordapp.com/attachments/315258983399161866/728993527857545246/unknown.png)

I'm running Ubuntu 20.04 with an NVIDIA RTX 2060, and the latest drivers.

**Comment by grondag** [comment]
Reproduced.   Fan of Lithos.  Will see what can be done.

**Comment by grondag** [comment]
![2020-07-05_20 15 05](https://user-images.githubusercontent.com/6106235/86552319-7dcf6000-befc-11ea-9c30-692e02df1c1f.png)

As good as I can do for now.  To make it perfect will require a companion resource pack.
