### ISSUE TITLE
Joining World text appearing over certain transparent objects

### ISSUE THREAD

**Issue by benjamin-bussey** [grondag/canvas#54]
Certain entities with transparent effects (clouds, water) will display the 'Joining World' text that appears while entering a server.

Mod version: canvas-mc116-1.0.771.jar

![2020-07-08_18 03 52](https://user-images.githubusercontent.com/14303414/86975254-eeb58880-c145-11ea-8104-d17a15e15252.png)
![2020-07-08_18 03 25](https://user-images.githubusercontent.com/14303414/86975257-ef4e1f00-c145-11ea-830a-30755d82c82e.png)
![2020-07-08_18 03 39](https://user-images.githubusercontent.com/14303414/86975259-efe6b580-c145-11ea-9ee2-ac2296ea1664.png)

**Comment by grondag** [comment]
Gotta be one of the funniest issues in recent memory. Thank you for reporting it.

**Comment by grondag** [comment]
So far been unable to reproduce this and not obvious where it would be happening.  Does it persist forever?  Any trick to make it happen?

Thanks.

**Comment by benjamin-bussey** [comment]
Upon doing a fresh multi-mc managed fabric install and re-adding all of the same mods, the rendering error has gone away. I have no idea what was causing this, but feel free to close the issues. I'll make a new issue if I manage to find what is causing this again.

**Comment by grondag** [comment]
Like a delicate spring flower, this wondrous defect has graced us briefly with its presence, only to fade away as the sun finds its rest.
