### ISSUE TITLE
Chests and Beds are invisible with this mod installed alongside lots of others.

### ISSUE THREAD

**Issue by Geneticus** [grondag/canvas#55]
I don't expect you to dig through my mess of a client :-D , but just in case I thought I'd give you the log for reference...
[2020-07-12-2.log.gz](https://github.com/grondag/canvas/files/4909524/2020-07-12-2.log.gz)
[latest.log](https://github.com/grondag/canvas/files/4909525/latest.log)

**Comment by grondag** [comment]
Canvas doesn't seem to be included in the list of loaded mods?

Note there was a bug in builds before 764 that could cause this.  Latest versions are available on CF:  https://www.curseforge.com/minecraft/mc-mods/canvas-renderer/files

**Comment by Geneticus** [comment]
I had 0.768 in the mods folder. I don't trust the modlist. It seems the minecraft logger gets a little confused when you are not running from the default .minecraft folder

**Comment by grondag** [comment]
I mean it's not in the list of mods that Fabric loader output the .log file.  Doesn't even mention Canvas.  It also shows that Indigo was loaded, which it would not be if Canvas were present.  Did you post the wrong log?

**Comment by Geneticus** [comment]
That's not only possible but quite probable!

**Comment by grondag** [comment]
Cannot reproduce in current build
