### ISSUE TITLE
No Overlays from other mods

### ISSUE THREAD

**Issue by BBloom81** [grondag/canvas#57]
Canvas does not allow other mods to render overlays (LightOverlay, Bounding Box Outline Reloaded, MiniHUD's shapes).

[latest.log](https://github.com/grondag/canvas/files/4926288/latest.log)

**Comment by JanThomas118** [comment]
I have just tried this out on my end trying to confirm your reports


Light overlay works just fine for me with the latest canvas and light overlay version.
Bounding Box Outline Reloaded does not work however. Enabling canvas makes all the bounding boxes dissapear.
MiniHUDs in world overlays do not work either as you have said.

**Comment by BBloom81** [comment]
> I have just tried this out on my end trying to confirm your reports
> 
> Light overlay works just fine for me with the latest canvas and light overlay version.
> Bounding Box Outline Reloaded does not work however. Enabling canvas makes all the bounding boxes dissapear.
> MiniHUDs in world overlays do not work either as you have said.


Interesting... I was on one version old of Light Overlay and updated, but found it still did not work.  So I started digging and realized that I had both Light Overlay and MiniHud's light level key mapped to the same key.  MiniHud was taking preference thus not displaying anything.

I apologize for the inaccurate report and thank you very much for getting me to dig deeper myself and discover that I'm not the brightest crayon in the box at all times.

I've now double checked BBOR and MiniHud and, as you know, those are not working.

Thank you again!

**Comment by grondag** [comment]
BBOR support should be fixed in [build 826](https://github.com/grondag/canvas/releases/download/1.0.826-unstable/canvas-mc116-1.0.826.jar)

MiniHud should also partially work - some debug renderers may not work because Canvas changes chunk rendering.

Please confirm and reopen if you find otherwise.

Thank you for the issue report.

**Comment by BBloom81** [comment]
@grondag 

Awesome!  BBOR works as does the despawn sphere with MiniHUD.

Only issue is, it broke Connected Block Textures, which worked properly with 784.

![2020-07-21_23 05 18](https://user-images.githubusercontent.com/65408805/88130609-f98e0580-cba8-11ea-9945-96f03ceeef3f.png)
 

The checkerboard is supposed to be glass.

**Comment by grondag** [comment]
CBT is fixed in build 830. Bit of a hack but gets the job done for now.
