### ISSUE TITLE
Incompatibility with OK Zoomer

### ISSUE THREAD

**Issue by EddyNottingham** [grondag/canvas#60]
Hello, I love Canvas so thank you for doing a great job with it! 

However, I have run into a little issue while trying to use OK Zoomer with it. I'm not sure if this is an issue with the OK Zoomer plugin, that imitates (to a much higher quality with added features) the Optifine zoom functionality, or if it is an issue with Canvas itself. 

I thought I should inform you of the issue here nonetheless.

Regards,
Eddy

**Comment by grondag** [comment]
Thank you for the thoughtful report.  Mod compatibility is important and I know many people find OK Zoomer useful.   Will add this to the list for compatibility work.

**Comment by JanThomas118** [comment]
Can you describe what is going wrong @EdwardNottingham ? 
I have installed the latest version of Ok Zoomer from curseforge (version 4.0.0) and haven't found any issues using the latest version of canvas.

**Comment by EddyNottingham** [comment]
I have done some debugging on my end, and I am a little embarrassed as I should have dove further down the rabbit-hole before reporting the issue. I have discovered that it is actually due to conflicting control bindings.

The odd thing that I found out, is that when using Sodium + OK Zoomer + Replay Mod everything worked fine. Even with the shortcut "C" conflicting with the base game and Replay Mod, and the shortcut "V" conflicting with just Replay Mod. Everything still just worked.

However, when I switched over to Canvas + OK Zoomer + Replay Mod, this was no longer the case. The keystrokes wouldn't register and so the only fix is to give OK Zoomer it's own bindings that are never used anywhere else.

I guess this isn't really an issue as users can expect to need to set fully independent keybindings, but maybe you have some insight into why this only happens with Canvas?

Thanks for the time you spent testing this earlier, and sorry for wasting your time with this not very important bug.

**Comment by JanThomas118** [comment]
I did try this: 
Install canvas, replay mod and ok zoomer: -> Default keybind 'c' for ok zoomer does not work.
Install sodium, replay mod and ok zoomer: -> Does not work either

Both times removing the conflicting vanilla keybind fixes it. So it seems to just be an oddity on your end?

**Comment by grondag** [comment]
Appears to be resolved,
