### ISSUE TITLE
blocks have seams

### ISSUE THREAD

**Issue by Linguardium** [grondag/canvas#64]
![image](https://user-images.githubusercontent.com/61733861/88207522-c5483280-cc04-11ea-8441-384f9132a499.png)

mc 1.16.1
loader 0.90.0
fapi 0.15.0
CPU Intel i3-8130U
Graphics (integrated) Intel UHD Graphics 620

will get f3 screenshots and modlist when i am back at the computer tonight

**Comment by grondag** [comment]
Not able to reproduce on vanilla blocks.  The looks like a mod is interfering somehow with texture baking or it's a precision issue with the Intel GPU. Unfortunately not yet able to reproduce in my main dev env.

More screenshots would indeed be helpful along with the mod list.

**Comment by Linguardium** [comment]
alright, so first video is a new bug (let me know if you want another bug report) showing vanilla resource pack, in a dark cave. it seems to be removing block rendering that are still in view.
the second video is [(SapixCraft 64x resource pack ](https://sapixcraft.com/) works flawlessly with all other mods i've tested) and you can see small seams. This is with fabric 0.90, fapi 0.15.1, and mc 1.16.1.  no other mods.
I am not sure what other mod makes the seams worse, but canvas is definitely putting them there

[Captures.zip](https://github.com/grondag/canvas/files/4963872/Captures.zip)
![2020-07-22_21 45 19](https://user-images.githubusercontent.com/61733861/88252994-07a15c00-cc65-11ea-9a12-8208b282e308.png)

**Comment by Linguardium** [comment]
alright, some extensive testing later and i cannot reproduce the first issue on a new instance with the exact same mod set.  Going to be trying to move config files over and see if there is something in there that does it.

**Comment by Linguardium** [comment]
going through mods, i can reproduce it _sometimes_ but it seems to be related to blockus and a bunch of unrelated mods :-/
I can always produce it with these mods in this seed in this location with limestone 

https://paste.ee/p/FhMPL

edit: can remove biospheres, its not a release version its a custom brew, basically i can add clearskies instead

seed: 123529062709140168
pos 98 60 -33
place limestone against the south wall instead of stone

**Comment by Danklor** [comment]
I have this issue with a large number of mods on a MacBook with Radeon Pro 560X. The problem does not occur with only Canvas and Fabric API. I am working to isolate which mod(s) trigger the conflict for me.

This shows up for me with Canvas versions 1.0.830 to current (.867), but does not affect 1.0.784 and earlier.

**Comment by Linguardium** [comment]
it seems to be related to model rendering specifically as the outline occurs across the modeled shapes. in the case of plants, this means that the cross sections are visible as well
![2020-07-27_16 06 08](https://user-images.githubusercontent.com/61733861/88600583-7135b780-d023-11ea-834d-bc7a10aea24c.png)

**Comment by Danklor** [comment]
I've attached the full log for a run showing the gaps between blocks with a minimal set of triggering mods. It seems that the exact mods used doesn't matter that much, but they need to add lots of block/model content. The exception to that rule may be "Astromine" which seems to be more likely to cause breakage than other mods with a similar block count.

![2020-07-28_10 36 06](https://user-images.githubusercontent.com/9893553/88681243-5b75d000-d0bf-11ea-8189-c78e9ddc76e5.png)

Note the foliage visible through the block gaps.

Log: 
[Seam_gaps.txt](https://github.com/grondag/canvas/files/4989018/Seam_gaps.txt)

**Comment by grondag** [comment]
This is happening in my primary dev env/world now.  Still no idea what is causing it but that will help isolate.
