### ISSUE TITLE
Rendering glitch when you fly up from the ground while looking down

### ISSUE THREAD

**Issue by yavincl** [grondag/canvas#67]
As it says on the tin. See it here:
https://youtu.be/LFnWS5NWv1s

```
==================  CANVAS RENDERER DEBUG INFORMATION ==================
Java: 14.0.2 64bit
CPU: 4x Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
GPU: Using framebuffer using OpenGL 3.0  3.2.2 build 10
OpenGL: GeForce GT 1030/PCIe/SSE2 GL version 4.6.0 NVIDIA 450.57, NVIDIA Corporation
GpuShader4: Y  VboArb: N  VaoEnabled: Y  VaoArb: N
(This message can be disabled by configuring logMachineInfo = false.)
========================================================================
```

**Comment by grondag** [comment]
Thank you for logging this.  I've noticed this myself and some causes have been fixed.  The terrain occluder is getting somehow getting confused and thinks no chunks are visible.  This has been mostly corrected but still (obviously) needs some tweaking.  Will leave this open until it is found and fixed.  

Could you please also add which Canvas version you were running when the example was recorded?

**Comment by yavincl** [comment]
1.0.831 on 1.16.1

**Comment by quat1024** [comment]
Might have regressed? i can reproduce this in Canvas 1.0.1598 for 1.17.

Another situation that causes it: looking straight up and flying down 👀

It makes the clouds turn blue too https://streamable.com/z6p7jc

**Comment by quat1024** [comment]
Also can sorta reproduce when flying sideways? Need to use something like `/tp @p ~ ~ ~ 90 0` to get your camera exactly axis-aligned, then you can see flickers when flying backwards across a chunk border.
