### ISSUE TITLE
Enhancement: smarter vine waving

### ISSUE THREAD

**Issue by supersaiyansubtlety** [grondag/canvas#68]
I noticed vines can sometimes clip into the block they're against:
![vine_jank](https://user-images.githubusercontent.com/618276/88723361-8ff88480-d0dd-11ea-969c-6a773d5a05fd.png)
Maybe prevent vine swaying if there's a block with a full-face (toward the vine) behind the vine that isn't a leaves block?

**Comment by spiralhalo** [comment]
This should be fixed in 542f049fc3eb8d811efc0b286a52f37cf822319f
