### ISSUE TITLE
Crash: EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by supersaiyansubtlety** [grondag/canvas#72]
Not sure if this is Canvas' fault, Canvas is just the only recognizable name I can see in the crash report. 

Here is the [crash report](https://pastebin.com/5FYtMsLF). 
Here is [latest.log](https://pastebin.com/2gzXUiEG). 
Here is the [client mod list](https://pastebin.com/CpA6Mz9Q)

Sorry I don't have solid details on how to reproduce it, except that I've been on a server (canvas is only on client, not server). It possibly happens when interacting and/or logging in.

**Comment by grondag** [comment]
Could you please retry this on latest build (929 or later) with MC 1.16.2 and confirm it still happens?

**Comment by supersaiyansubtlety** [comment]
It actually hasn't happened for a while even on 1.16.1 with canvas 1.0.830. The crash is so inconsistent I wouldn't be able say if it were fixed on the newer version without just playing with it for a few weeks (and I'm currently still on 1.16.1 waiting for some mods to update). 
Since it's not even clear that this is Canvas' fault I'd understand if you closed the issue.

**Comment by grondag** [comment]
Thanks for the update and please feel welcome to reopen or repost if it shows up again.
