### ISSUE TITLE
Wiki not updated to reflect changes in resource pack

### ISSUE THREAD

**Issue by tylerolson** [grondag/canvas#74]
Commit https://github.com/grondag/canvas/commit/b6c579e1a419605b02460e49c7f674478d87da11#diff-4b24171926ffc9e442ca5d17212f5904 changed the tutorial resource pack but was not edited in https://github.com/grondag/canvas/wiki/Quick-Start-Tutorial

**Comment by grondag** [comment]
Appears to be corrected in Wiki.
