### ISSUE TITLE
Support for performance and OpenGL 4.5

### ISSUE THREAD

**Issue by ghost** [grondag/canvas#79]
I would strongly like to ask for OpenGL 4.5 support, with `glMultiDrawArraysIndirect`, with bindless texturing, with sampler objects, with image2D support in compute post-processing shaders, rather than chasing support for older platforms as the only one possible… I generally want to offer support for OpenGL 4.5 or 4.6 with almost all of the innovations… I personally am not yet strong enough to develop such mods (overwhelmingly tired), but I have ideas in graphical APIs. Sodium already had a question about support for shaders, but it categorically states that they adhere to the idea of optimization… Well, they support several OpenGL modes, including older platforms… But here I would like to have a starting strip for my development of ray tracing for Minecraft (RTX support).

**Comment by grondag** [comment]
I have no philosophical objection to using newer OpenGL feature, but Canvas does aim to be compatible on all operating systems and common mid-tier+ hardware.  This inevitably means there must be multiple code paths built, tested and maintained.

That is the plan, actually, but it will have to wait until Canvas is feature complete and more stable in its overall design to avoid excessive rework and debugging that impedes overall progress.
