### ISSUE TITLE
Enchantment Glints not visible

### ISSUE THREAD

**Issue by grondag** [grondag/canvas#82]
inventory - armor, books, etc.  See CF and MultMC instance to duplicate

**Comment by CalXee** [comment]
Enchanted armor in third person or when other entities are wearing it looks fine. It's only inventory items and held/dropped items for me.

**Comment by grondag** [comment]
Fixed for vanilla items by https://github.com/grondag/canvas/commit/5527113c585a87e71275721501c9f14ad8bbc329.

Some modded  models with mixed materials may not render perfectly as items.
