### ISSUE TITLE
[1.16.2] Crash while browsing through REI with Canvas

### ISSUE THREAD

**Issue by Desempregago** [grondag/canvas#83]
The game doesn't generate a crash report, just a `Process crashed with exitcode -1073741819.` line at the end of the file. It doesn't even generate a hs_errorlog_xxx.log at the instance's root folder.

Using REI 5.2.7 + Canvas 1.0.878

**Comment by Desempregago** [comment]
NOTE: This doesn't seem to happen with the game in Windowed mode.

**Comment by Desempregago** [comment]
UPDATE: It does.

**Comment by Desempregago** [comment]
And again, it just generates a `Process crashed with exitcode -1073741819.` at the end of the log file.

**Comment by grondag** [comment]
Could you please attach log anyway?   May offer some clues.

**Comment by Desempregago** [comment]
[latest.log](https://github.com/grondag/canvas/files/5114816/latest.log)

the "Process crashed with exitcode -1073741819." entry does not appears in the log, only in the MultiMC console.

**Comment by Desempregago** [comment]
![Sem título](https://user-images.githubusercontent.com/14002834/90987430-72460000-e561-11ea-89be-704696bbf066.jpg)

**Comment by grondag** [comment]
Betting this is an AE2 compatibility issue.  Strange that it shows up this way.

There's a shortcoming in the Fabric render API that Gimpansor worked around by casting but Canvas has a different class. Will leave this open until confirmed.

**Comment by Desempregago** [comment]
Update: It's not Applied Energistics. Ran without it and the game crashed as soon as I switched to page 2.
Probably something related to item 3d models or enchantment glints?

Also, the `Process crashed with exitcode -1073741819.` log entry remains.

**Comment by Desempregago** [comment]
Sometimes while in the config screen the game also crashes.

**Comment by calloatti** [comment]
I have more info on this!

https://paste.ee/p/GtI6V

https://hastebin.com/raw/juvujugere

Both players have geforce videocards

and -1073741819 is FFFF FFFF C000 0005 in case you did not notice. The infamous windows buffer overrun/overflow

These crashes are using the AOF:Strawberry modpack https://www.curseforge.com/minecraft/modpacks/aof-strawberry

Both crashes are when using REI

I could not repro since I dont have a geforce card.

And AE2 is not in the modpack

**Comment by calloatti** [comment]
I see that OP also has a GeForce video card.

**Comment by shedaniel** [comment]
Here's someone else's crash log I have received:

https://paste.ee/p/1LF5h

Nvidia GeForce 1070

**Comment by grondag** [comment]
Thank you for the extra info.  Going to try some things to see if they help.

**Comment by calloatti** [comment]
For the record, one of the affected players says that removing canvas stops the crashing. Edit: The other player disabled REI to test and of course that stopped the crashes too.

**Comment by calloatti** [comment]
Another log. It does not include the actual crash but maybe the rest can be of use https://paste.gg/p/anonymous/ca352fac48ef442f969958780cd232a4

This is also the https://www.curseforge.com/minecraft/modpacks/aof-strawberry modpack

**Comment by Desempregago** [comment]
This time I got to catch a [pseudo-crashlog](https://pastebin.com/Jf7uwNAj).

**Comment by Fogrits** [comment]
UPDATE 2: and it REQUIRES the built-in Java that comes with the Minecraft Laucher

**Comment by grondag** [comment]
Still trying to isolate this problem.  It seems to be Nvidia-specific. Please try the following:

1. Turn off fast entry rendering in REI:
 ![image](https://user-images.githubusercontent.com/6106235/92309097-58d88700-ef57-11ea-81e7-cc43522beebc.png)
 
2. Ensure your Nvidia drivers are up to date. (This sort of crash seems to be fairly common with Nvidia drivers)
 
3. Make sure you are using the latest GitHub build for Canvas. (See releases.) There were some recent changes in Canvas item rendering to fix enchantment glint.  It's possible these might help but I doubt it.

**Comment by grondag** [comment]
Update:

Reviewing the available logs so far, this does appear to be an Nvidia driver issue that is triggered when REI uses the Immediate BufferBuilder to draw while Canvas is present.  

Disabling Faster Entry Rendering in the REI config (see above post) has worked for at least one user.

Another user reports no crashes using Nvidia driver 432.  Logs with crashes seem to have 445 or later.  So, an earlier driver or the latest [hot fix driver](https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/396210/announcing-geforce-hotfix-driver-45222-released-94/) may also be worth trying.

While this does appear to be driver-related, it only seems to happen when Canvas is present and so Canvas is doing _something_ that contributes to it.  Leaving open for that reason until it's confirmed the latest drivers don't break, or until the triggering condition can be discovered.

Please continue to report new information, including whether or not the config workaround or different drivers work for you.

**Comment by comp500** [comment]
I've replicated this, with NVIDIA driver 451.67, GTX 1650 hybrid (mobile) graphics, Canvas 1.0.989, REI 5.6.2. See the following hs_err_pid files: [hs_err_pid28228.log](https://github.com/grondag/canvas/files/5432404/hs_err_pid28228.log) [hs_err_pid28272.log](https://github.com/grondag/canvas/files/5432405/hs_err_pid28272.log) [hs_err_pid1428.log](https://github.com/grondag/canvas/files/5432413/hs_err_pid1428.log)
 (sometimes it doesn't give these - it just quits with exit code -1073741819)

The following steps reliably replicate the issue:
1. Set the game to GUI scale 1 - so all items are shown in REI
2. Maximise the game, so all items are shown in REI
3. Open REI

I have confirmed that disabling Faster Entry Rendering does fix the issue, and it occurs with only Canvas, REI and Fabric API.

I tried the latest Canvas GitHub build with the modpack I was using but got a `java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: grondag.canvas.apiimpl.material.MeshMaterialFinder.shader(ILgrondag/frex/api/material/MaterialShader;)Lgrondag/canvas/apiimpl/material/MeshMaterialFinder;` - I think the enchantment glint fixes are in 1.0.989 anyway.

I'll now try updating my NVIDIA graphics drivers and see if that also solves the issue.

Edit: Updated my NVIDIA drivers to 456.71 and it still occurs, and it also happens after downgrading to 442.74.

**Comment by flier268** [comment]
Same issue in newst build too(`java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: grondag.canvas.apiimpl.material.MeshMaterialFinder.shader(ILgrondag/frex/api/material/MaterialShader;)Lgrondag/canvas/apiimpl/material/MeshMaterialFinder;`)
My video card is NVIDIA 1060 3G

**Comment by supsm** [comment]
I don't think I can reproduce this issue with newer versions of canvas and rei. If nobody else can reproduce the issue this should be closed.
