### ISSUE TITLE
1.16.2 crash on worldjoin

### ISSUE THREAD

**Issue by drakosoldier298** [grondag/canvas#86]
https://gist.github.com/drakosoldier298/1ebc6d3e3a4696ae2d2c16355a5cfc17
IT will load until getting to join world. 
then crash, even with not enough crashes it still crashes my game.

**Comment by ramidzkh** [comment]
Looks like it's the same issue as #70 with AMD drivers

**Comment by grondag** [comment]
Appears to duplicate #70
