### ISSUE TITLE
Some pixels in textures aren't affected by bloom while some are, leading to odd bloom textures

### ISSUE THREAD

**Issue by CalXee** [grondag/canvas#87]
The torch texture has some pixels not blooming, as well as the bottom pixels in the beacon texture (but is less noticeable). If there is a way to make the entire torch texture bloom in a natural looking way that would be appreciated. Soul torches and campfires don't have this behaviour because of how Cold Glow works in contrast to Warm Glow. This effect appears in every shader but the effects seems to be amplified using this mod.
![2020-08-29_12 23 24](https://user-images.githubusercontent.com/68349758/91641447-799e5b00-e9f2-11ea-9c5a-44b571adf67c.png)
![2020-08-29_12 36 50](https://user-images.githubusercontent.com/68349758/91641714-5f657c80-e9f4-11ea-966c-3e9487e08ee6.png)

**Comment by supsm** [comment]
Fixed by #376
