### ISSUE TITLE
Bloom is visible through all entities

### ISSUE THREAD

**Issue by CalXee** [grondag/canvas#88]
Bloom can be seen through mobs and other entities like the book on the enchanting table, etc.
![2020-08-29_12 25 00](https://user-images.githubusercontent.com/68349758/91641496-c84bf500-e9f2-11ea-80c1-2154054b9eea.png)

**Comment by grondag** [comment]
This is being fixed as part of a significant refactor that will cause all entities to be rendered via shaders.  This is probably a few weeks out so leaving open but marking as "back burner" to set expectations.

**Comment by grondag** [comment]
This is fixed in recent Github builds.  A curseforge release will be posted relatively soon.
