### ISSUE TITLE
Shadows are Z-fighting/flickering

### ISSUE THREAD

**Issue by CalXee** [grondag/canvas#89]
Shadows flicker on the ground. I can't attach a video but if you move your camera around it would flicker.
![2020-08-29_12 26 57](https://user-images.githubusercontent.com/68349758/91641526-fcbfb100-e9f2-11ea-8c2f-8edc88517127.png)

**Comment by grondag** [comment]
Unable to reproduce in [build 913](https://github.com/grondag/canvas/releases/tag/1.0.913-unstable).  

If this is still happening, please post full Minecraft log including mod list (MultiMC log preferred) and will reopen.
