### ISSUE TITLE
Beacon beam transparency shifts with vertical camera angle.

### ISSUE THREAD

**Issue by CalXee** [grondag/canvas#90]
Looking up towards a beacon beam causes the side glow to be less transparent.
![2020-08-29_12 35 05](https://user-images.githubusercontent.com/68349758/91641690-2decb100-e9f4-11ea-95c9-5ea953af91de.png)
![2020-08-29_12 35 06](https://user-images.githubusercontent.com/68349758/91641691-2e854780-e9f4-11ea-86a1-73abf94db524.png)

**Comment by grondag** [comment]
Thank you for the report.  This is a vanilla bug.  It's not severe enough that I want to pursue it for Canvas.

https://bugs.mojang.com/browse/MC-112730
