### ISSUE TITLE
Crash with AE2 Blocks - 1.16.2

### ISSUE THREAD

**Issue by Topshelf2020** [grondag/canvas#99]
Placing blocks from AE2 crashes the game with Canvas installed. 

Canvas v. 1.0.878

All of Fabric 2.0.1

https://pastebin.com/UPJj4h3e

**Comment by grondag** [comment]
I suppose it would have helped if I had published the build that fixes this when it was available.  Should be on CF momentarily, or you can find the latest here: https://github.com/grondag/canvas/releases/download/1.0.927-unstable/canvas-mc116-1.0.927.jar
